samba4install - now removes samba4 download folder after updating.

diff --git a/serversetup/all/samba4/samba4install b/serversetup/all/samba4/samba4install
--- a/serversetup/all/samba4/samba4install
+++ b/serversetup/all/samba4/samba4install
@@ -2,19 +2,20 @@
 LOG_DATE=`date +%F`
 [ ! -d /opt/karoshi/logs/server_upgrades ] && mkdir -p /opt/karoshi/logs/server_upgrades
 echo `date` "Checking Samba4 version" >> /opt/karoshi/logs/server_upgrades/$LOG_DATE
+
 #Get the latest version
 
 [ ! -d /opt/karoshi/serversetup/all/samba4/download ] && mkdir /opt/karoshi/serversetup/all/samba4/download
-
 cd /opt/karoshi/serversetup/all/samba4/download
 
 LATESTVER=`lynx -dump http://ftp.samba.org/pub/samba/ | grep LATEST-IS-SAMBA- | sed -n 1,1p | cut -d"-" -f4 | cut -d" " -f1`
+
 #Check that we could get the latest version
-if [ -z $LATESTVER ]
+if [ -z "$LATESTVER" ]
 then
-echo Error - could not determine the latest samba version.
-echo "Error - could not determine the latest samba version." >> /opt/karoshi/logs/server_upgrades/$LOG_DATE
-exit 101
+	echo Error - could not determine the latest samba version.
+	echo "Error - could not determine the latest samba version." >> /opt/karoshi/logs/server_upgrades/$LOG_DATE
+	exit 101
 fi
 
 
@@ -22,33 +23,33 @@ fi
 
 if [ -f /usr/local/bin/samba-tool ]
 then
-CURRENTVER=`/usr/local/bin/samba-tool -V`
+	CURRENTVER=`/usr/local/bin/samba-tool -V`
 
-echo "Current Samba4 version: $CURRENTVER" | tee -a /opt/karoshi/logs/server_upgrades/$LOG_DATE
-echo "Latest Samba4 version: $LATESTVER" | tee -a /opt/karoshi/logs/server_upgrades/$LOG_DATE
+	echo "Current Samba4 version: $CURRENTVER" | tee -a /opt/karoshi/logs/server_upgrades/$LOG_DATE
+	echo "Latest Samba4 version: $LATESTVER" | tee -a /opt/karoshi/logs/server_upgrades/$LOG_DATE
 
-if [[ $CURRENTVER = $LATESTVER ]]
-then
-echo "Samba4 is up to date" | tee -a /opt/karoshi/logs/server_upgrades/$LOG_DATE
-exit
-fi
+	if [[ $CURRENTVER = $LATESTVER ]]
+	then
+		echo "Samba4 is up to date" | tee -a /opt/karoshi/logs/server_upgrades/$LOG_DATE
+		exit
+	fi
 
-LINE1=`echo -e "$CURRENTVER\n$LATESTVER" | sort -Vr | sed -n 1,1p`
+	LINE1=`echo -e "$CURRENTVER\n$LATESTVER" | sort -Vr | sed -n 1,1p`
 
-if [[ $LINE1 = $CURRENTVER ]]
-then
-echo "Current Samba4 version is ahead of the latest official version." | tee -a /opt/karoshi/logs/server_upgrades/$LOG_DATE
-exit
-fi
+	if [[ $LINE1 = $CURRENTVER ]]
+	then
+		echo "Current Samba4 version is ahead of the latest official version." | tee -a /opt/karoshi/logs/server_upgrades/$LOG_DATE
+		exit
+	fi
 
-if [[ $LINE1 = $LATESTVER ]]
-then
-echo "A samba4 upgrade is required." | tee -a /opt/karoshi/logs/server_upgrades/$LOG_DATE
+	if [[ $LINE1 = $LATESTVER ]]
+	then
+		echo "A samba4 upgrade is required." | tee -a /opt/karoshi/logs/server_upgrades/$LOG_DATE
+	else
+		exit
+	fi
 else
-exit
-fi
-else
-echo "Samba 4 needs installing." | tee -a /opt/karoshi/logs/server_upgrades/$LOG_DATE
+	echo "Samba 4 needs installing." | tee -a /opt/karoshi/logs/server_upgrades/$LOG_DATE
 fi
 
 #Install dependencies
@@ -61,8 +62,8 @@ wget http://ftp.samba.org/pub/samba/samba-$LATESTVER.tar.gz
 #Check that download was successful
 if [ $? != 0 ]
 then
-echo "Error - unable to download the latest samba4 version." | tee -a /opt/karoshi/logs/server_upgrades/$LOG_DATE
-exit 101
+	echo "Error - unable to download the latest samba4 version." | tee -a /opt/karoshi/logs/server_upgrades/$LOG_DATE
+	exit 101
 fi
 
 #Extracting samba
@@ -70,8 +71,8 @@ fi
 tar -xvf samba-$LATESTVER.tar.gz
 if [ $? != 0 ]
 then
-echo "Error -samba-$LATESTVER.tar.gz did not extract correctly." | tee -a /opt/karoshi/logs/server_upgrades/$LOG_DATE
-exit 101
+	echo "Error -samba-$LATESTVER.tar.gz did not extract correctly." | tee -a /opt/karoshi/logs/server_upgrades/$LOG_DATE
+	exit 101
 fi
 
 #Make sure that key.pem has the correct permissions
@@ -92,16 +93,16 @@ echo `date` "Configuring samba-$LATESTVER" | tee -a /opt/karoshi/logs/server_upg
 ./configure --enable-cups --with-ads --prefix=/usr/local --enable-fhs --sysconfdir=/etc --localstatedir=/var
 if [ $? != 0 ]
 then
-echo "Error -samba-$LATESTVER did not configure correctly." | tee -a /opt/karoshi/logs/server_upgrades/$LOG_DATE
-exit 101
+	echo "Error -samba-$LATESTVER did not configure correctly." | tee -a /opt/karoshi/logs/server_upgrades/$LOG_DATE
+	exit 101
 fi
 #Make
 echo `date` "Making samba-$LATESTVER" | tee -a /opt/karoshi/logs/server_upgrades/$LOG_DATE
 make -j $THREADS
 if [ $? != 0 ]
 then
-echo "Error -samba-$LATESTVER did not make correctly." | tee -a /opt/karoshi/logs/server_upgrades/$LOG_DATE
-exit 101
+	echo "Error -samba-$LATESTVER did not make correctly." | tee -a /opt/karoshi/logs/server_upgrades/$LOG_DATE
+	exit 101
 fi
 
 #Check to see if the current samba4 version is running
@@ -115,31 +116,34 @@ echo `date` "Installing samba-$LATESTVER" | tee -a /opt/karoshi/logs/server_upgr
 make install
 if [ $? != 0 ]
 then
-echo "Error -samba did not install correctly." | tee -a /opt/karoshi/logs/server_upgrades/$LOG_DATE
-exit 101
+	echo "Error -samba did not install correctly." | tee -a /opt/karoshi/logs/server_upgrades/$LOG_DATE
+	exit 101
 fi
 
 #Stop samba4
 if [ $RESTART_SAMBA = yes ]
 then
-echo `date` "Stopping samba4" | tee -a /opt/karoshi/logs/server_upgrades/$LOG_DATE
-/opt/karoshi/serversetup/distro/$DISTROCHOICE/scripts/control_services/samba_stop
-if [ $? != 0 ]
-then
-echo "Error -samba did not stop." | tee -a /opt/karoshi/logs/server_upgrades/$LOG_DATE
-exit
-fi
+	echo `date` "Stopping samba4" | tee -a /opt/karoshi/logs/server_upgrades/$LOG_DATE
+	/opt/karoshi/serversetup/distro/$DISTROCHOICE/scripts/control_services/samba_stop
+	if [ $? != 0 ]
+	then
+		echo "Error -samba did not stop." | tee -a /opt/karoshi/logs/server_upgrades/$LOG_DATE
+		exit
+	fi
 fi
 
 #Start samba4
 if [ $RESTART_SAMBA = yes ]
 then
-echo `date` "Starting samba4" | tee -a /opt/karoshi/logs/server_upgrades/$LOG_DATE
-/opt/karoshi/serversetup/distro/$DISTROCHOICE/scripts/control_services/samba_start
-if [ $? != 0 ]
-then
-echo "Error -samba did not start." | tee -a /opt/karoshi/logs/server_upgrades/$LOG_DATE
-exit
+	echo `date` "Starting samba4" | tee -a /opt/karoshi/logs/server_upgrades/$LOG_DATE
+	/opt/karoshi/serversetup/distro/$DISTROCHOICE/scripts/control_services/samba_start
+	if [ $? != 0 ]
+	then
+		echo "Error -samba did not start." | tee -a /opt/karoshi/logs/server_upgrades/$LOG_DATE
+		exit
+	fi
 fi
-fi
+
+#Remove download folder
+[ -d /opt/karoshi/serversetup/all/samba4/download ] && rm -f -R /opt/karoshi/serversetup/all/samba4/download
 exit
