Minor bugfixes for the gitlab module
This fixes an ssh configuration problem and provides more user feedback
during the installation process which is unavoidably lengthy due to
having to download and extract the gitlab files.

diff --git a/serversetup/modules/gitlab/setupgitlab b/serversetup/modules/gitlab/setupgitlab
--- a/serversetup/modules/gitlab/setupgitlab
+++ b/serversetup/modules/gitlab/setupgitlab
@@ -60,7 +60,9 @@ source /opt/karoshi/serversetup/distro/$DISTROCHOICE/all/software
 source /opt/karoshi/server_network/domain_information/domain_name
 [ -f /opt/karoshi/web_controls/user_prefs/$REMOTE_USER ] && source /opt/karoshi/web_controls/user_prefs/$REMOTE_USER
 
+PDCIP=$(net lookup `hostname-fqdn`)
 LDAPSERVER=127.0.0.1
+
 #Get ldap server to use
 if [ $(grep -c -w "kdc" /etc/krb5.conf) -gt 0 ]; then
 	LDAPSERVER=$(grep -w "kdc" /etc/krb5.conf | sed "s/ //g" | cut -d"=" -f2 | sed -n 1,1p)
@@ -74,6 +76,22 @@ fi
 /opt/karoshi/serversetup/distro/$DISTROCHOICE/scripts/startonboot/ssh
 /opt/karoshi/serversetup/distro/$DISTROCHOICE/scripts/startonboot/fail2ban
 
+showdots() {
+DOTCOUNT=1
+SHOWDOTS=yes
+while [[ $SHOWDOTS = yes ]]
+do
+	echo "." 
+	sleep 1
+	let DOTCOUNT=$DOTCOUNT+1
+	if [ $DOTCOUNT = 80 ]
+	then
+		echo "<br>"
+		DOTCOUNT=1
+	fi
+done
+}
+
 #####################
 #Add gitlab virtual host to apache
 #####################
@@ -82,7 +100,7 @@ RESTARTAPACHE=no
 [ -f /etc/apache2/sites-available/gitlab-ssl.conf ] || echo >> /etc/apache2/sites-available/gitlab-ssl.conf
 
 if [ $(grep -c "#gitlab-ssl virtual host" /etc/apache2/sites-available/gitlab-ssl.conf) == 0 ]; then
-	echo '<li>Configuring Gitlab apache virtual host.</li><br>'
+	echo '<ul><li>Configuring Gitlab apache virtual host.</li></ul>'
 	echo -e "#gitlab-ssl virtual host
 
 # Modules required:
@@ -187,7 +205,7 @@ if [ $(grep -c "<IfModule ssl_module>" /etc/apache2/ports.conf) == 0 ]; then
 fi
 
 if [ "$RESTARTAPACHE" == yes ]; then
-	echo '<li>Enabling required apache modules.</li><br>'
+	echo '<ul><li>Enabling required apache modules.</li></ul>'
 	# Add required apache modules
 	a2enmod rewrite &>/dev/null
 	a2enmod headers &>/dev/null
@@ -198,7 +216,7 @@ if [ "$RESTARTAPACHE" == yes ]; then
 	a2ensite gitlab-ssl.conf &>/dev/null
 
 	# Restart apache
-	echo '<li>Restarting apache to apply Gitlab support.</li><br>'
+	echo '<ul><li>Restarting apache to apply Gitlab support.</li></ul>'
 	/opt/karoshi/serversetup/distro/$DISTROCHOICE/scripts/control_services/apache_stop 1>/dev/null
 	sleep 1
 	/opt/karoshi/serversetup/distro/$DISTROCHOICE/scripts/control_services/apache_start 1>/dev/null
@@ -212,14 +230,14 @@ APPLYDEFAULT=no
 [ -f /etc/default/gitlab ] || echo >> /etc/default/gitlab
 
 if [ $(grep -c "#gitlab default configuration" /etc/default/gitlab) == 0 ]; then
-	echo '<li>Creating defaults file.</li><br>'
+	echo '<ul><li>Creating defaults file.</li></ul>'
 	echo -e '#gitlab default configuration
 gitlab_git_http_server_options="-listenUmask 0 -listenNetwork tcp -listenAddr localhost:50010 -authBackend http://127.0.0.1:50009"' >> /etc/default/gitlab
 	APPLYDEFAULT=yes
 fi
 
 if [ "$APPLYDEFAULT" == yes ]; then
-	echo '<li>Executing defaults file.</li><br>'
+	echo '<ul><li>Executing defaults file.</li></ul>'
 	". /etc/default/gitlab"
 fi
 
@@ -233,19 +251,19 @@ fi
 #	#File info does not show that this is a valid gzip so download the real thing.
 #	rm -f /opt/karoshi/serversetup/modules/gitlab/gitlab.tar.gz
 #	cd /opt/karoshi/serversetup/modules/gitlab
-#	echo '<li>'$"Downloading Gitlab archive"'</li><br>'
+#	echo '<ul><li>'$"Downloading Gitlab archive"'</li></ul>'
 #	wget https://github.com/the-linux-schools-project/karoshi-server/raw/master/serversetup/modules/gitlab/gitlab.tar.gz
 #	if [ $? != 0 ]
 #	then
 #		#We failed so bail out.
-#		echo '<li>'$"There was a problem downloading the archive"'</li><br>'
+#		echo '<ul><li>'$"There was a problem downloading the archive"'</li></ul>'
 #		sleep 5
 #		exit 101
 #	fi
 #	# Verify that the file is complete and that the correct file was downloaded
 #	checksum=$(md5sum "/opt/karoshi/serversetup/modules/gitlab/gitlab.tar.gz" | cut -d ' ' -f 1)
 #	if [ "$checksum" != "11da28c6d65a109e9c261920094b2cac" ]; then
-#		echo '<li>'$"There was a problem verifying the downloaded archive."'</li><br>'
+#		echo '<ul><li>'$"There was a problem verifying the downloaded archive."'</li></ul>'
 #		sleep 5
 #		exit 101
 #	fi
@@ -258,14 +276,14 @@ downloadgitlab="1"
 
 # Check whether the user has the tar.gz archive instead
 if [ -f /opt/karoshi/serversetup/modules/gitlab/gitlab.tar.gz ]; then
-	echo '<li>'$"Existing tar.gz archive discovered."'</li><br>'
+	echo '<ul><li>'$"Existing tar.gz archive discovered."'</li></ul>'
 	checksum=$(md5sum "/opt/karoshi/serversetup/modules/gitlab/gitlab.tar.gz" | cut -d ' ' -f 1)
 	if [ "$checksum" == "11da28c6d65a109e9c261920094b2cac" ]; then
 		# Valid gitlab.tar.gz archive exists
-		echo '<li>'$"Archive validated, skipping download."'</li><br>'
+		echo '<ul><li>'$"Archive validated, skipping download."'</li></ul><br>'
 		downloadgitlab="0"
 	else
-		echo '<li>'$"Archive invalid!"'</li><br>'
+		echo '<ul><li>'$"Archive invalid!"'</li></ul>'
 	fi
 fi
 
@@ -277,11 +295,18 @@ if [ "$downloadgitlab" == "1" ]; then
 		# The package does not exit and/or it is not valid
 		# Download Gitlab-CE 8.1.4 (Omnibus, Ubuntu Trusty amd64) Package from https://packages.gitlab.com/gitlab/gitlab-ce
 		rm -f /opt/karoshi/serversetup/modules/gitlab/gitlab.deb
-		wget -O /opt/karoshi/serversetup/modules/gitlab/gitlab.deb https://packages.gitlab.com/gitlab/gitlab-ce/packages/ubuntu/trusty/gitlab-ce_8.1.4-ce.0_amd64.deb/download
-		echo '<li>'$"Downloading Gitlab package from https://packages.gitlab.com/gitlab/gitlab-ce"'</li><br>'
-		if [ $? != 0 ]; then		
+
+		echo '<ul><li>'$"Downloading Gitlab package from https://packages.gitlab.com/gitlab/gitlab-ce"'</li></ul>'
+
+		showdots &
+		PID1=$!
+
+		wget -nv -O /opt/karoshi/serversetup/modules/gitlab/gitlab.deb https://packages.gitlab.com/gitlab/gitlab-ce/packages/ubuntu/trusty/gitlab-ce_8.1.4-ce.0_amd64.deb/download
+		STATUS=$?
+		kill $PID1
+		if [ $STATUS != 0 ]; then		
 			#We failed so bail out.
-			echo '<li>'$"There was a problem downloading the archive"'</li><br>'
+			echo '<ul><li>'$"There was a problem downloading the archive"'</li></ul>'
 			sleep 5
 			exit 101
 		fi
@@ -289,12 +314,12 @@ if [ "$downloadgitlab" == "1" ]; then
 		# Verify that the file is complete and that the correct file was downloaded
 		checksum=$(md5sum "/opt/karoshi/serversetup/modules/gitlab/gitlab.deb" | cut -d ' ' -f 1)
 		if [ "$checksum" != "2258ff0b53b0040ba884d913b42aa170" ]; then
-			echo '<li>'$"There was a problem verifying the downloaded archive."'</li><br>'
+			echo '<ul><li>'$"There was a problem verifying the downloaded archive."'</li></ul>'
 			sleep 5
 			exit 101
 		fi
 	else
-		echo '<li>'$"Existing .deb archive validated, skipping download."'</li><br>'
+		echo '<ul><li>'$"Existing .deb archive validated, skipping download."'</li></ul>'
 	fi
 fi
 
@@ -303,14 +328,18 @@ fi
 ###########################
 cd /opt/karoshi/.tempdata/
 
-echo '<li>'$"Extracting Gitlab"'</li><br>'
+echo '<ul><li>'$"Extracting Gitlab"'</li></ul>'
 mkdir /opt/karoshi/.tempdata/gitlab_temp
 #tar -xzf /opt/karoshi/serversetup/modules/gitlab/gitlab.tar.gz -C /opt/karoshi/.tempdata/gitlab_temp
 dpkg -x /opt/karoshi/serversetup/modules/gitlab/gitlab.deb /opt/karoshi/.tempdata/gitlab_temp &>/dev/null
 
 # Copy files into place
-echo '<li>'$"Copying Gitlab files into place - This may take a while."'</li><br>'
+echo '<ul><li>'$"Copying Gitlab files into place - This may take a while."'</li></ul>'
+
+showdots &
+PID1=$!
 cp -rf /opt/karoshi/.tempdata/gitlab_temp/opt/gitlab /opt/
+kill $PID1
 
 # Symlink gitlab-ctl
 /opt/gitlab/embedded/bin/symlink_ctl_cmds /opt/gitlab
@@ -328,7 +357,7 @@ rm -rf /opt/karoshi/.tempdata/gitlab_temp
 ###########################
 RECONFIGUREGITLAB=no
 if [ $(grep -c "#gitlab configuration" /etc/gitlab/gitlab.rb) == 0 ]; then
-	echo '<li>Creating Gitlab configuration file.</li><br>'
+	echo '<ul><li>Creating Gitlab configuration file.</li></ul>'
 	echo -e "#gitlab configuration" >> /etc/gitlab/gitlab.rb
 	echo -e "" >> /etc/gitlab/gitlab.rb
 	echo -e "external_url 'https://$ALIAS.$REALM:443'" >> /etc/gitlab/gitlab.rb
@@ -369,7 +398,7 @@ EOS" >> /etc/gitlab/gitlab.rb
 fi
 
 if [ "$RECONFIGUREGITLAB" == yes ]; then
-	echo '<li>'$"Reconfiguring and restarting Gitlab -  This may take a while."'</li><br>'
+	echo '<ul><li>'$"Reconfiguring and restarting Gitlab -  This may take a while."'</li></ul>'
 	gitlab-ctl reconfigure &>/dev/null
 	# Restart gitlab
 	/opt/karoshi/serversetup/distro/$DISTROCHOICE/scripts/control_services/gitlab_stop 1>/dev/null
@@ -382,7 +411,7 @@ fi
 RESTARTSSH=no
 
 if [ $(grep -c "AllowUsers" /etc/ssh/sshd_config) == 0 ]; then
-	echo -e "AllowUsers git root@$REMOTE_ADDR" >> /etc/ssh/sshd_config
+	echo -e "AllowUsers git root@$PDCIP" >> /etc/ssh/sshd_config
 	RESTARTSSH=yes
 fi
 
@@ -461,19 +490,19 @@ fi
 if [ "$ANNOUNCEPORTS" == yes ]; then
 	# Announce the changed ports
 	PORTLIST=${PORTLIST:1}
-	echo '<li>'$"The following extra ports are being allowed: TCP $PORTLIST"'</li><br>'
+	echo '<ul><li>'$"The following extra ports are being allowed: TCP $PORTLIST"'</li></ul>'
 fi
 
 if [ "$ANNOUNCECHANGE" == yes ]; then
 	# Announce the changed ssh rule
-	echo '<li>'$"Shorewall rule for TCP 22 changed to accept all (SSH access now restricted by sshd_config)"'</li><br>'
+	echo '<ul><li>'$"Shorewall rule for TCP 22 changed to accept all (SSH access now restricted by sshd_config)"'</li></ul>'
 fi
 
 ######################
 #Restart shorewall
 ######################
 if [ "$MOD_SHOREWALL" == yes ]; then
-	echo '<li>'$"Restarting shorewall"'</li><br>'
+	echo '<ul><li>'$"Restarting shorewall"'</li></ul>'
 	/opt/karoshi/serversetup/distro/$DISTROCHOICE/scripts/control_services/shorewall_stop 1>/dev/null
 	/opt/karoshi/serversetup/distro/$DISTROCHOICE/scripts/control_services/shorewall_start 1>/dev/null
 fi
@@ -500,7 +529,7 @@ fi
 #Restart fail2ban
 ######################
 if [ "$RESTARTFBAN" == yes ]; then
-	echo '<li>'$"Restarting fail2ban"'</li><br>'
+	echo '<ul><li>'$"Restarting fail2ban"'</li></ul>'
 	/opt/karoshi/serversetup/distro/$DISTROCHOICE/scripts/control_services/fail2ban_stop 1>/dev/null
 	/opt/karoshi/serversetup/distro/$DISTROCHOICE/scripts/control_services/fail2ban_start 1>/dev/null
 fi
@@ -509,7 +538,7 @@ fi
 # Add the chosen git certificates to root certificate chain
 # Fixes error: https://github.com/the-linux-schools-project/karoshi-server/issues/4
 #################################
-echo '<li>'$"Copying certificates into the root certificate chain."'</li><br>'
+echo '<ul><li>'$"Copying certificates into the root certificate chain."'</li></ul>'
 [ ! -d /usr/share/ca-certificates/gitlab ] && mkdir /usr/share/ca-certificates/gitlab 1>/dev/null
 
 [ ! -f "/usr/share/ca-certificates/gitlab/${ALIAS}.${REALM}.pem" ] && cp "/etc/ssl/apache/${ALIAS}.${REALM}.pem" "/usr/share/ca-certificates/gitlab" 1>/dev/null
@@ -525,7 +554,7 @@ then
 echo -e "gitlab/cacert.pem" >> /etc/ca-certificates.conf
 fi
 
-echo '<li>'$"Updating the root certificate chain."'</li><br>'
+echo '<ul><li>'$"Updating the root certificate chain."'</li></ul>'
 update-ca-certificates 1>/dev/null
 
 #################################
