Download gitlab archive from LFS
The setup for gitlab now checks that we have a valid archive in case it
is a placeholder for LFS and downloads it if needed. This allows the
module to be rolled out in a patch to existing servers. Other modules
could use the same method for saving space on the Karoshi Server iso
image.

diff --git a/serversetup/modules/gitlab/setupgitlab b/serversetup/modules/gitlab/setupgitlab
--- a/serversetup/modules/gitlab/setupgitlab
+++ b/serversetup/modules/gitlab/setupgitlab
@@ -224,6 +224,27 @@ if [ "$APPLYDEFAULT" == yes ]; then
 fi
 
 ###########################
+#Download gitlab.tar.gz if needed.
+###########################
+
+#We may only have a placeholder for the compressed image due to the file being in github LFS area.
+if [ $(file /opt/karoshi/serversetup/modules/gitlab/gitlab.tar.gz | grep -c gzip) = 0 ]
+then
+	#File info does not show that this is a valid gzip so download the real thing.
+	rm -f /opt/karoshi/serversetup/modules/gitlab/gitlab.tar.gz
+	cd /opt/karoshi/serversetup/modules/gitlab
+	echo '<li>'$"Downloading Gitlab archive"'</li><br>'
+	wget https://github.com/the-linux-schools-project/karoshi-server/raw/master/serversetup/modules/gitlab/gitlab.tar.gz
+	if [ $? != 0 ]
+	then
+		#We failed so bail out.
+		echo '<li>'$"There was a problem downloading the archive"'</li><br>'
+		sleep 5
+		exit 101
+	fi
+fi
+
+###########################
 #Extract gitlab
 ###########################
 cd /opt/karoshi/.tempdata/
