Download Gitlab-CE package from package host
The Gitlab-CE 8.1.4 (Omnibus, Ubuntu Trusty amd64) will now be downloaded from the host provided at the Gitlab website (https://packages.gitlab.com/gitlab/gitlab-ce). The existing file will be checked against an md5 checksum to test it's validity, if the package is invalid it will be (re)downloaded. The host is currently signed using HTTPS however if the package is downloaded, it will still be compared against an md5 checksum to check if the file is correct.

diff --git a/serversetup/modules/gitlab/setupgitlab b/serversetup/modules/gitlab/setupgitlab
--- a/serversetup/modules/gitlab/setupgitlab
+++ b/serversetup/modules/gitlab/setupgitlab
@@ -224,30 +224,71 @@ if [ "$APPLYDEFAULT" == yes ]; then
 fi
 
 ###########################
-#Download gitlab.tar.gz if needed.
+#Download gitlab.tar.gz if needed. (Legacy)
 ###########################
-
+#
 #We may only have a placeholder for the compressed image due to the file being in github LFS area.
-if [ $(file /opt/karoshi/serversetup/modules/gitlab/gitlab.tar.gz | grep -c gzip) = 0 ]
-then
-	#File info does not show that this is a valid gzip so download the real thing.
-	rm -f /opt/karoshi/serversetup/modules/gitlab/gitlab.tar.gz
-	cd /opt/karoshi/serversetup/modules/gitlab
-	echo '<li>'$"Downloading Gitlab archive"'</li><br>'
-	wget https://github.com/the-linux-schools-project/karoshi-server/raw/master/serversetup/modules/gitlab/gitlab.tar.gz
-	if [ $? != 0 ]
-	then
-		#We failed so bail out.
-		echo '<li>'$"There was a problem downloading the archive"'</li><br>'
-		sleep 5
-		exit 101
-	fi
-	# Verify that the file is complete and that the correct file was downloaded
+#if [ $(file /opt/karoshi/serversetup/modules/gitlab/gitlab.tar.gz | grep -c gzip) = 0 ]
+#then
+#	#File info does not show that this is a valid gzip so download the real thing.
+#	rm -f /opt/karoshi/serversetup/modules/gitlab/gitlab.tar.gz
+#	cd /opt/karoshi/serversetup/modules/gitlab
+#	echo '<li>'$"Downloading Gitlab archive"'</li><br>'
+#	wget https://github.com/the-linux-schools-project/karoshi-server/raw/master/serversetup/modules/gitlab/gitlab.tar.gz
+#	if [ $? != 0 ]
+#	then
+#		#We failed so bail out.
+#		echo '<li>'$"There was a problem downloading the archive"'</li><br>'
+#		sleep 5
+#		exit 101
+#	fi
+#	# Verify that the file is complete and that the correct file was downloaded
+#	checksum=$(md5sum "/opt/karoshi/serversetup/modules/gitlab/gitlab.tar.gz" | cut -d ' ' -f 1)
+#	if [ "$checksum" != "11da28c6d65a109e9c261920094b2cac" ]; then
+#		echo '<li>'$"There was a problem verifying the downloaded archive."'</li><br>'
+#		sleep 5
+#		exit 101
+#	fi
+#fi
+
+###########################
+#Download gitlab.deb package if needed.
+###########################
+downloadgitlab="1"
+
+# Check whether the user has the tar.gz archive instead
+if [ -f /opt/karoshi/serversetup/modules/gitlab/gitlab.tar.gz ]; then
 	checksum=$(md5sum "/opt/karoshi/serversetup/modules/gitlab/gitlab.tar.gz" | cut -d ' ' -f 1)
 	if [ "$checksum" != "11da28c6d65a109e9c261920094b2cac" ]; then
-		echo '<li>'$"There was a problem verifying the downloaded archive."'</li><br>'
-		sleep 5
-		exit 101
+		# Valid gitlab.tar.gz archive exists
+		downloadgitlab="0"
+	fi
+fi
+
+if [ "$downloadgitlab" == "1" ]; then
+	[ ! -f /opt/karoshi/serversetup/modules/gitlab/gitlab.deb ] && echo -e "" >> /opt/karoshi/serversetup/modules/gitlab/gitlab.deb
+	checksum=$(md5sum "/opt/karoshi/serversetup/modules/gitlab/gitlab.deb" | cut -d ' ' -f 1)
+	
+	if [ "$checksum" != "2258ff0b53b0040ba884d913b42aa170" ]; then
+		# The package does not exit and/or it is not valid
+		# Download Gitlab-CE 8.1.4 (Omnibus, Ubuntu Trusty amd64) Package from https://packages.gitlab.com/gitlab/gitlab-ce
+		rm -f /opt/karoshi/serversetup/modules/gitlab/gitlab.deb
+		wget -O /opt/karoshi/serversetup/modules/gitlab/gitlab.deb https://packages.gitlab.com/gitlab/gitlab-ce/packages/ubuntu/trusty/gitlab-ce_8.1.4-ce.0_amd64.deb/download
+		echo '<li>'$"Downloading Gitlab package from https://packages.gitlab.com/gitlab/gitlab-ce"'</li><br>'
+		if [ $? != 0 ]; then		
+			#We failed so bail out.
+			echo '<li>'$"There was a problem downloading the archive"'</li><br>'
+			sleep 5
+			exit 101
+		fi
+		
+		# Verify that the file is complete and that the correct file was downloaded
+		checksum=$(md5sum "/opt/karoshi/serversetup/modules/gitlab/gitlab.deb" | cut -d ' ' -f 1)
+		if [ "$checksum" != "2258ff0b53b0040ba884d913b42aa170" ]; then
+			echo '<li>'$"There was a problem verifying the downloaded archive."'</li><br>'
+			sleep 5
+			exit 101
+		fi
 	fi
 fi
 
@@ -258,7 +299,8 @@ cd /opt/karoshi/.tempdata/
 
 echo '<li>'$"Extracting Gitlab"'</li><br>'
 mkdir /opt/karoshi/.tempdata/gitlab_temp
-tar -xzf /opt/karoshi/serversetup/modules/gitlab/gitlab.tar.gz -C /opt/karoshi/.tempdata/gitlab_temp
+#tar -xzf /opt/karoshi/serversetup/modules/gitlab/gitlab.tar.gz -C /opt/karoshi/.tempdata/gitlab_temp
+dpkg -x /opt/karoshi/serversetup/modules/gitlab/gitlab.deb /opt/karoshi/.tempdata/gitlab_temp &>/dev/null
 
 # Copy files into place
 echo '<li>'$"Copying Gitlab files into place - This make take a while."'</li><br>'
