karoshi_gluster - fix to improve reliability in adding bricks to an existing volume.

diff --git a/serversetup/modules/glusterfs/scripts/karoshi_gluster b/serversetup/modules/glusterfs/scripts/karoshi_gluster
--- a/serversetup/modules/glusterfs/scripts/karoshi_gluster
+++ b/serversetup/modules/glusterfs/scripts/karoshi_gluster
@@ -265,7 +265,7 @@ do
 	then
 		echo `date`: "karoshi_gluster peer probe $MAINSERVER - $NEWSERVER" >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
 		gluster peer probe "$NEWSERVER"
-		echo "<br>"
+		echo "<br><br>"
 		#Make sure that peer probe is successful
 		PCOUNTER=1
 		sleep 1
@@ -284,7 +284,7 @@ do
 		echo `date`: "karoshi_gluster peer probe $NEWSERVER - $MAINSERVER" >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
 		ssh -o PasswordAuthentication=no -o ConnectTimeout=3 $NEWSERVER '
 		gluster peer probe '"$MAINSERVER"'
-		echo "<br>"
+		echo "<br><br>"
 		#Make sure that peer probe is successfull
 		PCOUNTER=1
 		sleep 1
@@ -301,6 +301,51 @@ do
 			echo `date`: "karoshi_gluster peer probe failure for $NEWSERVER - $MAINSERVER" >> /opt/karoshi/logs/karoshi_web_management/'$LOG_DATE'
 			sleep 5
 			exit 101
+		fi
+
+		#Check that the server is appearing as a peer in all servers in the pool
+		if [ -d /opt/karoshi/server_network/gluster-volumes/$VOLUME/servers/ ]
+		then
+			for CURRENTSERVER in `ls -1 /opt/karoshi/server_network/gluster-volumes/$VOLUME/servers`
+			do
+				if [ $CURRENTSERVER = `hostname-fqdn` ]
+				then
+					PCOUNTER=1
+					while  [ `gluster peer status | grep -c $NEWSERVER` = 0 ]
+					do
+						sleep 1
+						let PCOUNTER=$PCOUNTER+1
+						if [ $PCOUNTER = 30 ]
+						then
+							echo "<li>"$CURRENTSERVER - $NEWSERVER $"Gluster peer probe failure""</li>"
+							echo `date`: "karoshi_gluster peer probe failure for $CURRENTSERVER - $NEWSERVER" >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
+							sleep 5
+							exit 101
+					fi
+					done
+				else
+
+
+					ssh -o PasswordAuthentication=no -o ConnectTimeout=3 $CURRENTSERVER '
+					#Make sure that peer probe is successfull
+					PCOUNTER=1
+					sleep 1
+					while  [ `gluster peer status | grep -c '$NEWSERVER'` = 0 ]
+					do
+						sleep 1
+						let PCOUNTER=$PCOUNTER+1
+						[ $PCOUNTER = 30 ] && exit 101
+					done
+					'	
+					if [ $? = 101 ]
+					then
+						echo "<li>"$CURRENTSERVER - $NEWSERVER $"Gluster peer probe failure""</li>"
+						echo `date`: "karoshi_gluster peer probe failure for $CURRENTSERVER - $MAINSERVER" >> /opt/karoshi/logs/karoshi_web_management/'$LOG_DATE'
+						sleep 5
+						exit 101
+					fi	
+				fi
+			done
 		fi
 	fi
 done
@@ -447,6 +492,7 @@ then
 
 	#Add gluster brick to volume
 	gluster volume add-brick $VOLUME replica $BRICKCOUNT $SERVER:$GLUSTERBASE/$VOLUME force
+	echo "<br>"
 
 	#Mount the drive
 	mount_volume
