karoshi_gluster - fix for peer probe for new servers. sysvsupport - fix for missing sysv scripts. setupowncloud - language fix.

diff --git a/serversetup/modules/glusterfs/scripts/karoshi_gluster b/serversetup/modules/glusterfs/scripts/karoshi_gluster
--- a/serversetup/modules/glusterfs/scripts/karoshi_gluster
+++ b/serversetup/modules/glusterfs/scripts/karoshi_gluster
@@ -26,7 +26,6 @@ LOG_DATE=`date +%F`
 TYPE=replica
 MOUNTBASE=/mnt-gluster
 GLUSTERBASE=/home/gluster-volumes
-
 SERVERLIST=$1
 VOLUME=$2
 ACTION=$3
@@ -259,51 +258,51 @@ done
 function add_to_pool {
 
 #Add servers to pool
-for SERVER in `echo $SERVERLIST | sed 's/,/ /g'`
+for NEWSERVER in `echo $SERVERLIST | sed 's/,/ /g'`
 do
-	#Peer probe all servers
-	for PROBESERVER in `echo $SERVERLIST | sed 's/,/ /g'`
-	do
-		if [ $SERVER != $PROBESERVER ]
-		then
-			echo '<li>'$SERVER - $PROBESERVER' - '$"Probing server"'</li><br>'
-			if [ $SERVER = `hostname-fqdn` ]
+	MAINSERVER=`hostname-fqdn`
+	if [ $NEWSERVER != "$MAINSERVER" ]
+	then
+		echo `date`: "karoshi_gluster peer probe $MAINSERVER - $NEWSERVER" >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
+		gluster peer probe "$NEWSERVER"
+		echo "<br>"
+		#Make sure that peer probe is successful
+		PCOUNTER=1
+		sleep 1
+		while  [ `gluster peer status | grep -c $NEWSERVER` = 0 ]
+		do
+			sleep 1
+			let PCOUNTER=$PCOUNTER+1
+			if [ $PCOUNTER = 20 ]
 			then
-				gluster peer probe $PROBESERVER
-				#Make sure that peer probe is successfull
-				PCOUNTER=1
-				sleep 1
-				while  [ `gluster peer status | grep -c $PROBESERVER` = 0 ]
-				do
-					sleep 1
-					let PCOUNTER=$PCOUNTER+1
-					if [ $PCOUNTER = 20 ]
-					then
-						echo `date`: "karoshi_gluster peer probe failure for $PROBESERVER" >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
-						exit 101
-					fi
-				done
-			else
-				ssh -o PasswordAuthentication=no -o ConnectTimeout=3 $SERVER '
-				gluster peer probe '$PROBESERVER'
-				#Make sure that peer probe is successfull
-				PCOUNTER=1
-				sleep 1
-				while  [ `gluster peer status | grep -c '$PROBESERVER'` = 0 ]
-				do
-					sleep 1
-					let PCOUNTER=$PCOUNTER+1
-					[ $PCOUNTER = 20 ] && exit 101
-				done
-				'
-				if [ $? = 101 ]
-				then
-					echo `date`: "karoshi_gluster peer probe failure for '$PROBESERVER'" >> /opt/karoshi/logs/karoshi_web_management/'$LOG_DATE'
-					exit 101
-				fi
+				echo "<li>"$MAINSERVER - $NEWSERVER $"Gluster peer probe failure""</li>"
+				echo `date`: "karoshi_gluster peer probe failure for $MAINSERVER - $NEWSERVER" >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
+				sleep 5
+				exit 101
 			fi
+		done
+		echo `date`: "karoshi_gluster peer probe $NEWSERVER - $MAINSERVER" >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
+		ssh -o PasswordAuthentication=no -o ConnectTimeout=3 $NEWSERVER '
+		gluster peer probe '"$MAINSERVER"'
+		echo "<br>"
+		#Make sure that peer probe is successfull
+		PCOUNTER=1
+		sleep 1
+		while  [ `gluster peer status | grep -c '$PROBESERVER'` = 0 ]
+		do
+			sleep 1
+			let PCOUNTER=$PCOUNTER+1
+			[ $PCOUNTER = 20 ] && exit 101
+		done
+		'	
+		if [ $? = 101 ]
+		then
+			echo "<li>"$NEWSERVER - $MAINSERVER $"Gluster peer probe failure""</li>"
+			echo `date`: "karoshi_gluster peer probe failure for $NEWSERVER - $MAINSERVER" >> /opt/karoshi/logs/karoshi_web_management/'$LOG_DATE'
+			sleep 5
+			exit 101
 		fi
-	done
+	fi
 done
 }
 
@@ -413,8 +412,6 @@ fi
 if [ $ACTION = add ]
 then
 	SERVER=$SERVERLIST
-	SERVERLIST=`ls -1 /opt/karoshi/server_network/gluster-volumes/$VOLUME/servers/`
-	SERVERLIST=$SERVERLIST,$SERVER
 	echo '<li>'$SERVER' - '$"Adding server to gluster volume"' - '$VOLUME'</li><br>'
 
 	#Open shorewall ports and make sure that glusterfs is running
