Main Server Restore mode
Restore mode added to main server install options.
Joins to an existing domain controller and restores dc-data.

diff --git a/serversetup/modules/glusterfs/scripts/karoshi_gluster b/serversetup/modules/glusterfs/scripts/karoshi_gluster
--- a/serversetup/modules/glusterfs/scripts/karoshi_gluster
+++ b/serversetup/modules/glusterfs/scripts/karoshi_gluster
@@ -281,6 +281,7 @@ do
 				exit 101
 			fi
 		done
+		echo main server is $MAINSERVER new server is $NEWSERVER server is $SERVER
 		echo `date`: "karoshi_gluster peer probe $NEWSERVER - $MAINSERVER" >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
 		ssh -o PasswordAuthentication=no -o ConnectTimeout=3 $NEWSERVER '
 		gluster peer probe '"$MAINSERVER"'
@@ -298,11 +299,10 @@ do
 		if [ $? = 101 ]
 		then
 			echo "<li>"$NEWSERVER - $MAINSERVER $"Gluster peer probe failure""</li>"
-			echo `date`: "karoshi_gluster peer probe failure for $NEWSERVER - $MAINSERVER" >> /opt/karoshi/logs/karoshi_web_management/'$LOG_DATE'
+			echo `date`: "karoshi_gluster peer probe failure for $NEWSERVER - $MAINSERVER" >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
 			sleep 5
 			exit 101
 		fi
-
 		#Check that the server is appearing as a peer in all servers in the pool
 		if [ -d /opt/karoshi/server_network/gluster-volumes/$VOLUME/servers/ ]
 		then
@@ -310,39 +310,43 @@ do
 			do
 				if [ $CURRENTSERVER = `hostname-fqdn` ]
 				then
-					PCOUNTER=1
-					while  [ `gluster peer status | grep -c $NEWSERVER` = 0 ]
-					do
+					if [ $CURRENTSERVER != $NEWSERVER ]
+					then
+						PCOUNTER=1
+						while  [ `gluster peer status | grep -c $NEWSERVER` = 0 ]
+						do
+							sleep 1
+							let PCOUNTER=$PCOUNTER+1
+							if [ $PCOUNTER = 30 ]
+							then
+								echo "<li>"$CURRENTSERVER - $NEWSERVER $"Gluster peer probe failure""</li>"
+								echo `date`: "karoshi_gluster peer probe failure for $CURRENTSERVER - $NEWSERVER" >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
+								sleep 5
+								exit 101
+						fi
+						done
+					fi
+				else
+					if [ $CURRENTSERVER != $NEWSERVER ]
+					then
+						ssh -o PasswordAuthentication=no -o ConnectTimeout=3 $CURRENTSERVER '
+						#Make sure that peer probe is successfull
+						PCOUNTER=1
 						sleep 1
-						let PCOUNTER=$PCOUNTER+1
-						if [ $PCOUNTER = 30 ]
+						while  [ `gluster peer status | grep -c '$NEWSERVER'` = 0 ]
+						do
+							sleep 1
+							let PCOUNTER=$PCOUNTER+1
+							[ $PCOUNTER = 30 ] && exit 101
+						done
+						'	
+						if [ $? = 101 ]
 						then
 							echo "<li>"$CURRENTSERVER - $NEWSERVER $"Gluster peer probe failure""</li>"
-							echo `date`: "karoshi_gluster peer probe failure for $CURRENTSERVER - $NEWSERVER" >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
+							echo `date`: "karoshi_gluster peer probe failure for $CURRENTSERVER - $MAINSERVER" >> /opt/karoshi/logs/karoshi_web_management/'$LOG_DATE'
 							sleep 5
 							exit 101
-					fi
-					done
-				else
-
-
-					ssh -o PasswordAuthentication=no -o ConnectTimeout=3 $CURRENTSERVER '
-					#Make sure that peer probe is successfull
-					PCOUNTER=1
-					sleep 1
-					while  [ `gluster peer status | grep -c '$NEWSERVER'` = 0 ]
-					do
-						sleep 1
-						let PCOUNTER=$PCOUNTER+1
-						[ $PCOUNTER = 30 ] && exit 101
-					done
-					'	
-					if [ $? = 101 ]
-					then
-						echo "<li>"$CURRENTSERVER - $NEWSERVER $"Gluster peer probe failure""</li>"
-						echo `date`: "karoshi_gluster peer probe failure for $CURRENTSERVER - $MAINSERVER" >> /opt/karoshi/logs/karoshi_web_management/'$LOG_DATE'
-						sleep 5
-						exit 101
+						fi
 					fi	
 				fi
 			done
@@ -544,7 +548,9 @@ then
 	if [ $SERVER = `hostname-fqdn` ]
 	then
 			#Create folder for gluster volume
-			[ ! -d $GLUSTERBASE ] && mkdir -p $GLUSTERBASE/$VOLUME
+			[ ! -d $GLUSTERBASE/$VOLUME ] && mkdir -p $GLUSTERBASE/$VOLUME
+			echo creating $GLUSTERBASE/$VOLUME
+			ls -l $GLUSTERBASE
 			[ ! -d $MOUNTBASE ] && mkdir -p $MOUNTBASE
 			echo '<li>'$HOSTNAME'.'$REALM' - '$"stopping glusterfs"'</li><br>'
 			/opt/karoshi/serversetup/distro/$DISTROCHOICE/scripts/control_services/glusterfs_stop 1>/dev/null
