GlusterFS support - Additional domain controllers can now use glusterfs.
This support is experimental and is not enabled by default.

To enable create an empty file before adding any other servers:
touch /opt/karoshi/serversetup/variables/glusterfs

Adding an additional domain controller will now automatically create gluster volumes for:

/var/lib/samba/netlogon
/var/lib/samba/sysvol
/home/applications

diff --git a/serversetup/modules/glusterfs/scripts/karoshi_gluster b/serversetup/modules/glusterfs/scripts/karoshi_gluster
--- a/serversetup/modules/glusterfs/scripts/karoshi_gluster
+++ b/serversetup/modules/glusterfs/scripts/karoshi_gluster
@@ -29,6 +29,8 @@ SERVERLIST=$1
 VOLUME=$2
 FOLDERPATH=$3
 ACTION=$4
+REMOTE_USER=$5
+REMOTE_ADDR=$6
 
 function usage {
 echo -e "karoshi_gluster usage:\n\nkaroshi_gluster serverlist volume folderpath action\n\nserverlist - comma separated list of servers to create the gluster volume on.\n\nvolume - the name of the volume to create.\n\nfolderpath - the path to the that you want to convert to a glusterfs volume.\n\naction: create/add\n\ncreate: create a new gluster volume\nadd: add a new server to an existing volume.\n\nExample 1: Create a new glusterfs volume\n\nkaroshi_gluster server1.mydomain.com,server2.mydomain.com netlogon /var/lib/samba/netlogon create\n\nExample 2: An an extra server to a glusterfs volume\n\nkaroshi_gluster server3.mydomain.com netlogon /var/lib/samba/netlogon add\n"
@@ -63,13 +65,15 @@ echo `date`: karoshi_gluster serverlist:$SERVERLIST volume:$VOLUME folderpath:$F
 source /opt/karoshi/server_network/domain_information/domain_name
 PORTS=111,24007:24009,49152:49200,34865:34867
 
+echo "<br><br><li><b>Configure GlusterFS - $VOLUME</b></li><br>"
+
 #Make sure glusterfs is running
 source /opt/karoshi/serversetup/variables/distro
 /opt/karoshi/serversetup/distro/$DISTROCHOICE/scripts/startonboot/glusterfs
 /opt/karoshi/serversetup/distro/$DISTROCHOICE/scripts/control_services/glusterfs_status
 if [ $? != 0 ]
 then
-echo "<li> $HOSTNAME.$REALM - starting glusterfs</li>"
+echo "<li> $HOSTNAME.$REALM - starting glusterfs</li><br>"
 /opt/karoshi/serversetup/distro/$DISTROCHOICE/scripts/control_services/glusterfs_start
 fi
 
@@ -83,7 +87,7 @@ COUNTER=0
 #Check to see if a volume already exists with that name
 if [ `gluster volume info $VOLUME 2>/dev/null | grep -c $VOLUME` != 0 ]
 then
-echo "<li> $SERVER: $VOLUME - a volume with this name already exists</li>"
+echo "<li> $SERVER: $VOLUME - a volume with this name already exists</li><br>"
 exit 101
 fi
 
@@ -99,7 +103,7 @@ then
 #Open ports on firewall
 if [ `grep -c "#karoshi_gluster" /etc/shorewall/rules` = 0 ]
 then
-echo "<li>$SERVER - Opening ports for glusterfs</li>"
+echo "<li>$SERVER - Opening ports for glusterfs</li><br>"
 
 LINENUM=`grep -n 'LAST LINE -- ADD YOUR ENTRIES BEFORE THIS ONE -- DO NOT REMOVE' /etc/shorewall/rules | cut -d: -f1`
 sed -i $LINENUM'c'\ACCEPT'	'net'	'fw'	'tcp'	'$PORTS'	'-'#'karoshi_gluster /etc/shorewall/rules
@@ -122,7 +126,7 @@ source /opt/karoshi/serversetup/variables/distro
 #Open ports on firewall
 if [ `grep -c "#karoshi_gluster" /etc/shorewall/rules` = 0 ]
 then
-echo "<li>'$SERVER' - Opening ports for glusterfs</li>"
+echo "<li>'$SERVER' - Opening ports for glusterfs</li><br>"
 
 LINENUM=`grep -n "LAST LINE -- ADD YOUR ENTRIES BEFORE THIS ONE -- DO NOT REMOVE" /etc/shorewall/rules | cut -d: -f1`
 sed -i $LINENUM"c"\ACCEPT"	"net"	"fw"	"tcp"	"'$PORTS'"	"-"#"karoshi_gluster /etc/shorewall/rules
@@ -142,12 +146,30 @@ fi
 /opt/karoshi/serversetup/distro/$DISTROCHOICE/scripts/control_services/glusterfs_status
 if [ $? != 0 ]
 then
-echo "<li> '$SERVER' - starting glusterfs</li>"
+echo "<li> '$SERVER' - starting glusterfs</li><br>"
 /opt/karoshi/serversetup/distro/$DISTROCHOICE/scripts/control_services/glusterfs_start
 fi
-gluster peer probe '$HOSTNAME.$REALM'
 '
 gluster peer probe $SERVER
+
+ssh -o PasswordAuthentication=no -o ConnectTimeout=3 $SERVER '
+gluster peer probe '$HOSTNAME.$REALM'
+'
+#Make sure that peer probe is successfull
+PCOUNTER=1
+sleep 1
+while  [ `gluster peer status | grep -c $SERVER` = 0 ]
+do
+	sleep 1
+	let PCOUNTER=$PCOUNTER+1
+	if [ $PCOUNTER = 20 ]
+	then
+		echo `date`: "karoshi_gluster peer probe failure for $SERVER" >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
+		exit 101
+	fi
+done
+
+
 fi
 
 let COUNTER=$COUNTER+1
@@ -155,11 +177,11 @@ let COUNTER=$COUNTER+1
 done
 
 #Create glusterfs volume
-echo "<li>Creating GlusterFS volume for $VOLUME</li>"
+echo "<li>Creating GlusterFS volume for $VOLUME</li><br>"
 gluster volume create $VOLUME $TYPE $COUNTER $GLUSTERCLUSTER force
 if [ $? != 0 ]
 then
-echo "<li>There was a problem creating the volume for $VOLUME</li>"
+echo "<li>There was a problem creating the volume for $VOLUME</li><br>"
 exit 101
 fi
 #Start Gluster volume
@@ -167,7 +189,7 @@ echo "<li>Starting GlusterFS volume for $VOLUME</li>"
 gluster volume start $VOLUME
 if [ $? != 0 ]
 then
-echo "<li>There was a problem starting the volume for $VOLUME</li>"
+echo "<li>There was a problem starting the volume for $VOLUME</li><br>"
 exit 101
 fi
 
@@ -181,14 +203,14 @@ then
 #Move folder path if it exists
 if [ -d $FOLDERPATH ]
 then
-echo "<li>$SERVER - Backing up $FOLDERPATH</li>"
+echo "<li>$SERVER - Backing up $FOLDERPATH</li><br>"
 mv $FOLDERPATH $FOLDERPATH.pregluster.$$
 fi
 
 #Create empty folder to mount to 
 [ ! -d $FOLDERPATH ] && mkdir -p $FOLDERPATH
 #Mount volume
-echo "<li>'$SERVER' - Mounting '$FOLDERPATH'</li>"
+echo "<li>'$SERVER' - Mounting '$FOLDERPATH'</li><br>"
 mount -t glusterfs $SERVER:/$VOLUME $FOLDERPATH
 
 #Add entry to fstab
@@ -231,7 +253,7 @@ ssh -o PasswordAuthentication=no -o ConnectTimeout=3 $SERVER '
 #Move folder path if it exists
 if [ -d '$FOLDERPATH' ]
 then
-echo "<li>'$SERVER' - Backing up '$FOLDERPATH'</li>"
+echo "<li>'$SERVER' - Backing up '$FOLDERPATH'</li><br>"
 mv '$FOLDERPATH' '$FOLDERPATH'.pregluster.'$$'
 fi
 
@@ -239,7 +261,7 @@ fi
 [ ! -d '$FOLDERPATH' ] && mkdir -p '$FOLDERPATH'
 
 #Mount volume
-echo "<li>'$SERVER' - Mounting '$FOLDERPATH'</li>"
+echo "<li>'$SERVER' - Mounting '$FOLDERPATH'</li><br>"
 mount -t glusterfs '$SERVER':/'$VOLUME' '$FOLDERPATH'
 
 #Add entry to fstab
@@ -278,14 +300,14 @@ exit" > /etc/rc2.d/S99mount_gluster_shares
 chmod 0755 /etc/rc2.d/S99mount_gluster_shares
 '
 fi
-echo GlusterFS Server > /opt/karoshi/server_network/servers/$SERVER/gluster_server
+echo GlusterFS Server"<br>" > /opt/karoshi/server_network/servers/$SERVER/glusterfs_server
 done
 
 #Restrict access to the gluster volume
 gluster volume set $VOLUME auth.allow 127.0.0.1
 
 #Copy in data to gluster cluster
-echo "<li>`hostname-fqdn` - Copying in existing data to '$FOLDERPATH'</li>"
+echo "<li>`hostname-fqdn` - Copying in existing data to '$FOLDERPATH'</li><br>"
 cp -f -R $FOLDERPATH.pregluster.$$/* $FOLDERPATH/ 
 
 fi
@@ -297,7 +319,7 @@ fi
 if [ $ACTION = add ]
 then
 SERVER=$SERVERLIST
-echo "<li>$SERVER - Adding server to $VOLUME gluster volume"
+echo "<li>$SERVER - Adding server to $VOLUME gluster volume</li><br>"
 #Start gluster on the remote server
 ssh -o PasswordAuthentication=no -o ConnectTimeout=3 $SERVER '
 
@@ -306,7 +328,7 @@ source /opt/karoshi/serversetup/variables/distro
 #Open ports on firewall
 if [ `grep -c "#karoshi_gluster" /etc/shorewall/rules` = 0 ]
 then
-echo "<li>'$SERVER' - Opening ports for glusterfs</li>"
+echo "<li>'$SERVER' - Opening ports for glusterfs</li><br>"
 
 LINENUM=`grep -n "LAST LINE -- ADD YOUR ENTRIES BEFORE THIS ONE -- DO NOT REMOVE" /etc/shorewall/rules | cut -d: -f1`
 sed -i $LINENUM"c"\ACCEPT"	"net"	"fw"	"tcp"	"'$PORTS'"	"-"#"karoshi_gluster /etc/shorewall/rules
@@ -318,32 +340,63 @@ echo "#"LAST LINE -- ADD YOUR ENTRIES BEFORE THIS ONE -- DO NOT REMOVE >> /etc/s
 
 fi
 
-#Delete brick folder if it exists
-[ -d '$FOLDERPATH'-gluster ] && rm -f -R '$FOLDERPATH'-gluster
-
 #Make sure glusterfs is running
 source /opt/karoshi/serversetup/variables/distro
 /opt/karoshi/serversetup/distro/$DISTROCHOICE/scripts/startonboot/glusterfs
 /opt/karoshi/serversetup/distro/$DISTROCHOICE/scripts/control_services/glusterfs_status
 if [ $? != 0 ]
 then
-echo "<li> '$SERVER' - starting glusterfs</li>"
+echo "<li> '$SERVER' - starting glusterfs</li><br>"
 /opt/karoshi/serversetup/distro/$DISTROCHOICE/scripts/control_services/glusterfs_start
 fi
-echo "<li>$SERVER - probing server - in ssh</li>"
-gluster peer probe '$HOSTNAME.$REALM'
-echo "<li>$SERVER - probing server completed - in ssh</li>"
+
+#Check to see if this server is already in the volume
+if [ `gluster volume info '$VOLUME' | grep -c "'$SERVER':"` != 0 ]
+then
+#This server is already in the volume
+exit 101
+fi
+
+#Delete brick folder if it exists
+[ -d '$FOLDERPATH'-gluster ] && rm -f -R '$FOLDERPATH'-gluster
+
 '
+if [ $? = 101 ]
+then
+echo `date`: "karoshi_gluster $SERVER is already in the volume" >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
+exit
+fi
+
 #Add server to pool
-echo "<li>$SERVER - probing server</li>"
+echo "<li>$SERVER - probing server</li><br>"
 gluster peer probe $SERVER
-echo boo
-echo "<li>$SERVER - getting brick count</li>"
+
+ssh -o PasswordAuthentication=no -o ConnectTimeout=3 $SERVER '
+echo "<li>'$SERVER' - probing server</li><br>"
+gluster peer probe '$HOSTNAME.$REALM'
+echo "<li>'$SERVER' - probing server completed</li><br>"
+'
+
+#Make sure that peer probe is successfull
+PCOUNTER=1
+sleep 1
+while  [ `gluster peer status | grep -c $SERVER` = 0 ]
+do
+	sleep 1
+	let PCOUNTER=$PCOUNTER+1
+	if [ $PCOUNTER = 20 ]
+	then
+		echo `date`: "karoshi_gluster peer probe failure for $SERVER" >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
+		exit 101
+	fi
+done
+
+echo "<li>$SERVER - getting brick count</li><br>"
 #Get current number of bricks in the volume
-BRICKCOUNT=`gluster volume info netlogon | grep "Bricks: " | cut -d"=" -f2 | sed 's/ //g'`
+BRICKCOUNT=`gluster volume info $VOLUME | grep "Bricks: " | cut -d"=" -f2 | sed 's/ //g'`
 let BRICKCOUNT=$BRICKCOUNT+1
 
-echo "<li> '$SERVER' - adding $FOLDERPATH-gluster to $VOLUME $</li>"
+echo "<li> '$SERVER' - adding $FOLDERPATH-gluster to $VOLUME $</li><br>"
 
 #gluster volume add-brick $VOLUME  replica $$BRICKCOUNT $SERVER:/$FOLDERPATH-gluster
 gluster volume add-brick $VOLUME replica $BRICKCOUNT $SERVER:$FOLDERPATH-gluster force
@@ -352,8 +405,20 @@ gluster volume add-brick $VOLUME replica $BRICKCOUNT $SERVER:$FOLDERPATH-gluster
 #Mount the drive
 ssh -o PasswordAuthentication=no -o ConnectTimeout=3 $SERVER '
 source /opt/karoshi/serversetup/variables/distro
+
+#Move folder path if it exists
+if [ -d '$FOLDERPATH' ]
+then
+echo "<li>'$SERVER' - Backing up '$FOLDERPATH'</li><br>"
+mv '$FOLDERPATH' '$FOLDERPATH'.pregluster.'$$'
+fi
+
+#Create empty folder to mount to 
+[ ! -d '$FOLDERPATH' ] && mkdir -p '$FOLDERPATH'
+
+
 #Mount volume
-echo "<li>'$SERVER' - Mounting '$FOLDERPATH'</li>"
+echo "<li>'$SERVER' - Mounting '$FOLDERPATH'</li><br>"
 mount -t glusterfs '$SERVER':/'$VOLUME' '$FOLDERPATH'
 
 #Add entry to fstab
@@ -393,7 +458,7 @@ chmod 0755 /etc/rc2.d/S99mount_gluster_shares
 
 
 '
-echo GlusterFS Server > /opt/karoshi/server_network/servers/$SERVER/gluster_server
+echo GlusterFS Server"<br>" > /opt/karoshi/server_network/servers/$SERVER/glusterfs_server
 
 fi
 
