Samba3 support removed in the web management.
Prior to this the latest version of the web management could be installed on a server still running samba3.
Since we are no longer doing any testing on samba3 this has now been removed and the samba4 scripts have now been moved back to the normal folders.

diff --git a/serversetup/web_controls/scripts/exec/pdc/delete_user b/serversetup/web_controls/scripts/exec/pdc/delete_user
--- a/serversetup/web_controls/scripts/exec/pdc/delete_user
+++ b/serversetup/web_controls/scripts/exec/pdc/delete_user
@@ -71,12 +71,12 @@ then
 echo `date`: delete_user - Not called by delete_user.cgi >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
 exit 101
 fi
-if [ $REMOTE_USER'null' = null ]
+if [ -z "$REMOTE_USER" ]
 then
 echo `date`: delete_user - Blank remote user >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
 exit 101
 fi
-if [ $REMOTE_ADDR'null' = null ]
+if [ -z "$REMOTE_ADDR" ]
 then
 echo `date`: delete_user - Blank remote tcpip address >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
 exit 101
@@ -86,16 +86,6 @@ if [ `grep -c ^$REMOTE_USER: /opt/karoshi/web_controls/web_access_admin` != 1 ]
 then
 echo `date`: delete_user - access denied to $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
 exit 101
-fi
-
-#Check for slave ldap servers
-SLAVE_LDAP_SERVERS=no
-if [ -d /opt/karoshi/server_network/slave_ldap_servers/ ]
-then
-if [ `ls -1 /opt/karoshi/server_network/slave_ldap_servers/ | wc -l` -gt 0 ]
-then
-SLAVE_LDAP_SERVERS=yes
-fi
 fi
 
 #Check for federated ldap servers
@@ -121,72 +111,6 @@ fi
 source /opt/karoshi/server_network/group_information/$PRIMARYGROUP
 echo `date`: delete_user - deleting $DELETEUSER from $REMOTE_ADDR by $REMOTE_USER >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
 
-#######################
-#Check all servers are up before deleting the user
-#######################
-#Check slave ldap servers
-if [ $SLAVE_LDAP_SERVERS = yes ]
-then
-for SLAVELDAPSERVERS in /opt/karoshi/server_network/slave_ldap_servers/*
-do
-SLAVELDAPSERVER=`basename $SLAVELDAPSERVERS`
-SSHSTATUS=0
-ssh -o PasswordAuthentication=no -o ConnectTimeout=2 $SLAVELDAPSERVER ls 1>/dev/null
-SSHSTATUS=`echo $?`
-if [ $SSHSTATUS != 0 ]
-then
-echo `date`: delete_user - user not deleted due to ssh failure on $SLAVELDAPSERVER by $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
-exit 105
-fi
-done
-fi
-
-#Check federated servers
-if [ $FEDERATED_LDAP_SERVERS = yes ]
-then
-for FEDERATEDLDAPSERVERS in /opt/karoshi/server_network/federated_ldap_servers/*
-do
-FEDERATEDLDAPSERVER=`basename $FEDERATEDLDAPSERVERS`
-SSHSTATUS=0
-ssh -o PasswordAuthentication=no -o ConnectTimeout=2  $FEDERATEDLDAPSERVER '
-#Check to see if the users home area should be on a separate file server in this area.
-source /opt/karoshi/server_network/group_information/'$PRIMARYGROUP'
-if [ -d /opt/karoshi/server_network/servers/$SERVER ] && [ $SERVER != $HOSTNAME ]
-then
-ssh -x -o PasswordAuthentication=no -o ConnectTimeout=2 $SERVER ls 1>/dev/null
-SSHSTATUS=`echo $?`
-if [ $SSHSTATUS != 0 ]
-then
-exit 106
-fi
-fi
-'
-SSHSTATUS=`echo $?`
-if [ $SSHSTATUS != 0 ]
-then
-if [ $SSHSTATUS = 106 ]
-then
-echo `date`: delete_user - user not deleted due to ssh failure on a file server connected from $FEDERATEDLDAPSERVER by $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
-exit 105
-else
-echo `date`: delete_user - user not deleted due to ssh failure on $FEDERATEDLDAPSERVER by $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
-exit 105
-fi
-fi
-done
-fi
-
-#Check file server is up for user's home area
-if [ -d /opt/karoshi/server_network/servers/$SERVER ] && [ $SERVER != $HOSTNAME ]
-then
-ssh -o PasswordAuthentication=no -o ConnectTimeout=2 -o ConnectTimeout=2 $SERVER ls 1>/dev/null
-SSHSTATUS=`echo $?`
-if [ $SSHSTATUS != 0 ]
-then
-echo `date`: delete_user - user not created due to ssh failure on $SERVER by $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
-exit 105
-fi
-fi
 
 #######################
 #Delete user image
@@ -195,14 +119,14 @@ fi
 #######################
 #Delete the user account
 #######################
-smbldap-userdel $DELETEUSER 1>> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE 2>> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
+samba-tool user delete $DELETEUSER 1>> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE 2>> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
 DELETE_USER_STATUS=`echo $?`
 if [ -d /home/applications/profiles/$DELETEUSER ]
 then
 #Delete profile if using a roaming profile
 rm -d -R -f /home/applications/profiles/$DELETEUSER
 rm -f /home/applications/profiles/$DELETEUSER.V2
-smbldap-groupdel $DELETEUSER 1>> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE 2>> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
+samba-tool group delete $DELETEUSER 1>> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE 2>> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
 if [ `grep -w -c $DELETEUSER /opt/karoshi/server_network/windows_roaming_profile_users` -gt 0 ]
 then
 LINENUMBER=`grep -w -n ^$DELETEUSER /opt/karoshi/server_network/windows_roaming_profile_users | cut -d: -f1`
@@ -214,22 +138,12 @@ fi
 fi
 #Delete logon script
 [ -f /var/lib/samba/netlogon/windows_settings/drives/$DELETEUSER.kix ] && rm -f /var/lib/samba/netlogon/windows_settings/drives/$DELETEUSER.kix
-#Delete security settings
-[ -f /var/lib/samba/netlogon/windows_settings/security/$DELETEUSER.kix ] && rm -f /var/lib/samba/netlogon/windows_settings/security/$DELETEUSER.kix
+
 #Delete home folder
 [ -d $HOMEPATH/$DELETEUSER ] && rm -f -R $HOMEPATH/$DELETEUSER
-#Delete inbox
-[ -f /var/spool/mail/$DELETEUSER ] && rm -f /var/spool/mail/$DELETEUSER
+
 #Delete group information
 [ -f /opt/karoshi/server_network/group_information/$DELETEUSER ] && rm -f /opt/karoshi/server_network/group_information/$DELETEUSER
-#Rebuild primarygroups.txt - this file is to allow for windows 7 logins where the primary group feature is broken
-[ -f /var/lib/samba/netlogon/primarygroups.txt ] && rm -f /var/lib/samba/netlogon/primarygroups.txt
-for USERDETAILS in `getent passwd | grep /home/users/`
-do
-KAROSHIUSER=`echo $USERDETAILS | cut -d: -f1 | sed 's/,//g'`
-PRIGROUP=`id -g -n $KAROSHIUSER`
-echo $KAROSHIUSER,$PRIGROUP >> /var/lib/samba/netlogon/primarygroups.txt
-done
 
 #######################
 #Delete the folder on extra file server
@@ -237,26 +151,39 @@ done
 if [ -d /opt/karoshi/server_network/servers/$SERVER ] && [ $SERVER != $HOSTNAME ]
 then
 ssh -x -o PasswordAuthentication=no $SERVER 'rm -f -R '$HOMEPATH''/''$DELETEUSER'' 1>> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE 2>> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
+SSHSTATUS=`echo $?`
+if [ $SSHSTATUS != 0 ]
+then
+echo `date`: delete_user - $DELETEUSER ssh failure on $SERVER by $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
+echo $SERVER,fileserver,delete >> /opt/karoshi/server_network/offline_servers/delete_users/$DELETEUSER
+FAILED_SERVER=yes
+FAILEDSERVERLIST=$FAILEDSERVERLIST,$SERVER
+fi
 fi
 
 #######################
-#Delete the account on any slave ldap servers
+#Delete the account on any email servers
 #######################
-
-if [ $SLAVE_LDAP_SERVERS = yes ]
+if [ -f /opt/karoshi/server_network/emailserver ]
 then
-for SLAVELDAPSERVERS in /opt/karoshi/server_network/slave_ldap_servers/*
-do
-SLAVELDAPSERVER=`basename $SLAVELDAPSERVERS`
-echo `date`: delete_user - deleting $DELETEUSER on $SLAVELDAPSERVER from $REMOTE_ADDR by $REMOTE_USER >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
-ssh -x -o PasswordAuthentication=no $SLAVELDAPSERVER '
-smbldap-userdel -r '$DELETEUSER'
-#Delete home folder
-[ -d '$HOMEPATH''/''$DELETEUSER' ] && rm -f -R '$HOMEPATH''/''$DELETEUSER'
-#Delete inbox
-[ -f /var/spool/mail/'$DELETEUSER' ] && rm -f /var/spool/mail/'$DELETEUSER'
-' 1>> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE 2>> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
-done
+EMAILSERVER=`sed -n 1,1p /opt/karoshi/server_network/emailserver`
+if [ $EMAILSERVER != $HOSTNAME ]
+then 
+ssh -o PasswordAuthentication=no -o ConnectTimeout=3 $EMAILSERVER '
+rm -f -R /home/users/email/'$DELETEUSER'
+rm -f -R '$HOMEPATH''/''$DELETEUSER'
+'
+SSHSTATUS=`echo $?`
+if [ $SSHSTATUS != 0 ]
+then
+echo `date`: delete_user - $DELETEUSER ssh failure on $SERVER by $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
+echo $EMAILSERVER,emailserver,delete >> /opt/karoshi/server_network/offline_servers/delete_users/$DELETEUSER
+FAILED_SERVER=yes
+FAILEDSERVERLIST=$FAILEDSERVERLIST,$SERVER
+fi
+else
+rm -f -R /home/users/email/$DELETEUSER
+fi
 fi
 
 #######################
@@ -274,7 +201,7 @@ if [ -d /home/applications/profiles/'$DELETEUSER' ]
 then
 #Delete profile if using a roaming profile
 rm -d -R -f /home/applications/profiles/'$DELETEUSER'
-smbldap-groupdel '$DELETEUSER' 1>> /opt/karoshi/logs/karoshi_web_management/'$LOG_DATE' 2>> /opt/karoshi/logs/karoshi_web_management/'$LOG_DATE'
+samba-tool group delete '$DELETEUSER' 1>> /opt/karoshi/logs/karoshi_web_management/'$LOG_DATE' 2>> /opt/karoshi/logs/karoshi_web_management/'$LOG_DATE'
 if [ `grep -w -c '$DELETEUSER' /opt/karoshi/server_network/windows_roaming_profile_users` -gt 0 ]
 then
 LINENUMBER=`grep -w -n ^'$DELETEUSER' /opt/karoshi/server_network/windows_roaming_profile_users | cut -d: -f1`
@@ -284,12 +211,9 @@ sed -i $LINENUMBER"d" /opt/karoshi/server_network/windows_roaming_profile_users
 sed -i "/^$/d" /opt/karoshi/server_network/windows_roaming_profile_users
 fi
 fi
-#Delete home folder from file server
+
 source /opt/karoshi/server_network/group_information/'$PRIMARYGROUP'
-if [ -d /opt/karoshi/server_network/servers/$SERVER ] && [ $SERVER != $HOSTNAME ]
-then
-ssh -x -o PasswordAuthentication=no $SERVER "rm -f -R '$HOMEPATH'/'$DELETEUSER'" 1>> /opt/karoshi/logs/karoshi_web_management/'$LOG_DATE' 2>> /opt/karoshi/logs/karoshi_web_management/'$LOG_DATE'
-fi
+
 #Delete logon script
 [ -f /var/lib/samba/netlogon/windows_settings/drives/'$DELETEUSER'.kix ] && rm -f /var/lib/samba/netlogon/windows_settings/drives/'$DELETEUSER'.kix
 #Delete security settings
@@ -297,29 +221,49 @@ fi
 #Delete group information
 [ -f /opt/karoshi/server_network/group_information/'$DELETEUSER' ] && rm -f /opt/karoshi/server_network/group_information/'$DELETEUSER'
 #Delete user from ldap
-smbldap-userdel -r '$DELETEUSER'
+samba-tool user delete '$DELETEUSER'
 #Delete home folder
 [ -d '$HOMEPATH''/''$DELETEUSER' ] && rm -f -R '$HOMEPATH''/''$DELETEUSER'
 #Delete inbox
 [ -f /var/spool/mail/'$DELETEUSER' ] && rm -f /var/spool/mail/'$DELETEUSER'
 
-#Delete user from any federated slave ldap servers
-if [ -d /opt/karoshi/server_network/slave_ldap_servers/ ]
+#######################
+#Delete the folder on extra file server
+#######################
+if [ -d /opt/karoshi/server_network/servers/$SERVER ] && [ $SERVER != $HOSTNAME ]
 then
-if [ `ls -1 /opt/karoshi/server_network/slave_ldap_servers/ | wc -l` -gt 0 ]
+ssh -x -o PasswordAuthentication=no $SERVER "rm -f -R '$HOMEPATH''/''$DELETEUSER'" 1>> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE 2>> /opt/karoshi/logs/karoshi_web_management/'$LOG_DATE'
+SSHSTATUS=`echo $?`
+if [ $SSHSTATUS != 0 ]
 then
-for SLAVELDAPSERVERS in /opt/karoshi/server_network/slave_ldap_servers/*
-do
-SLAVELDAPSERVER=`basename $SLAVELDAPSERVERS`
-echo `date`: delete_user \(federated mode\) - deleting $DELETEUSER on $SLAVELDAPSERVER from '$REMOTE_ADDR' by '$REMOTE_USER' >> /opt/karoshi/logs/karoshi_web_management/'$LOG_DATE'
-ssh -x -o PasswordAuthentication=no $SLAVELDAPSERVER "
-smbldap-userdel -r '$DELETEUSER'
-#Delete home folder
-[ -d '$HOMEPATH'/'$DELETEUSER' ] && rm -f -R '$HOMEPATH'/'$DELETEUSER'
-#Delete inbox
-[ -f /var/spool/mail/'$DELETEUSER' ] && rm -f /var/spool/mail/'$DELETEUSER'
-" 1>> /opt/karoshi/logs/karoshi_web_management/'$LOG_DATE' 2>> /opt/karoshi/logs/karoshi_web_management/'$LOG_DATE'
-done
+echo `date`: delete_user - '$DELETEUSER' ssh failure on $SERVER by $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/'$LOG_DATE'
+echo $SERVER,fileserver,delete >> /opt/karoshi/server_network/offline_servers/delete_users/'$DELETEUSER'
+FAILED_SERVER=yes
+FAILEDSERVERLIST=$FAILEDSERVERLIST,$SERVER
+fi
+fi
+
+#######################
+#Delete the account on any email servers
+#######################
+if [ -f /opt/karoshi/server_network/emailserver ]
+then
+EMAILSERVER=`sed -n 1,1p /opt/karoshi/server_network/emailserver`
+if [ $EMAILSERVER != $HOSTNAME ]
+then 
+ssh -o PasswordAuthentication=no -o ConnectTimeout=3 $EMAILSERVER "
+rm -f -R /home/users/email/'$DELETEUSER'
+"
+SSHSTATUS=`echo $?`
+if [ $SSHSTATUS != 0 ]
+then
+echo `date`: delete_user - '$DELETEUSER' ssh failure on $SERVER by $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/'$LOG_DATE'
+echo $SERVER,emailserver >> /opt/karoshi/server_network/offline_servers/delete_users/'$DELETEUSER'
+FAILED_SERVER=yes
+FAILEDSERVERLIST=$FAILEDSERVERLIST,$SERVER
+else
+rm -f -R /home/users/email/'$DELETEUSER'
+fi
 fi
 fi
 
@@ -327,13 +271,14 @@ fi
 [ -f /var/lib/samba/netlogon/primarygroups.txt ] && rm -f /var/lib/samba/netlogon/primarygroups.txt
 for USERDETAILS in `getent passwd | grep /home/users/`
 do
-KAROSHIUSER=`echo $USERDETAILS | cut -d: -f1 | sed "s/,//g"`
+KAROSHIUSER=`echo $USERDETAILS | cut -d: -f1 | sed 's/,//g'`
 PRIGROUP=`id -g -n $KAROSHIUSER`
 echo $KAROSHIUSER,$PRIGROUP >> /var/lib/samba/netlogon/primarygroups.txt
 done
 ' 1>> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE 2>> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
 done
 fi
+
 
 #Delete request file if this user has been requested by a member of staff
 if [ $REQUESTFILE'null' != null ]
@@ -380,29 +325,4 @@ then
 /opt/karoshi/serversetup/web_controls/scripts/web_management_warn delete acceptable_use_authorisations
 fi
 fi
-
-#######################
-#Delete the account on any email servers
-#######################
-if [ -f /opt/karoshi/server_network/emailserver ]
-then
-EMAILSERVER=`sed -n 1,1p /opt/karoshi/server_network/emailserver`
-if [ $EMAILSERVER != $HOSTNAME ]
-then 
-ssh -o PasswordAuthentication=no -o ConnectTimeout=3 $EMAILSERVER '
-rm -f -R /home/users/email/'$DELETEUSER'
-'
-SSHSTATUS=`echo $?`
-if [ $SSHSTATUS != 0 ]
-then
-echo `date`: delete_user - $DELETEUSER ssh failure on $SERVER by $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
-echo $SERVER,emailserver >> /opt/karoshi/server_network/offline_servers/delete_users/$DELETEUSER
-FAILED_SERVER=yes
-FAILEDSERVERLIST=$FAILEDSERVERLIST,$SERVER
-fi
-else
-rm -f -R /home/users/email/$DELETEUSER
-fi
-fi
-
 exit $DELETE_USER_STATUS
diff --git a/serversetup/web_controls/scripts/exec/pdc/module_federation_control b/serversetup/web_controls/scripts/exec/pdc/module_federation_control
--- a/serversetup/web_controls/scripts/exec/pdc/module_federation_control
+++ b/serversetup/web_controls/scripts/exec/pdc/module_federation_control
@@ -25,22 +25,7 @@
 #Website: http://www.karoshi.org.uk
 LOG_DATE=`date +%F`
 [ $LOG_DATE'null' = null ] && exit
-########################
-#Check md5checksum
-########################
-if ! test -f /opt/karoshi/web_controls/checksums/admin_checksums/module_federation_control_cgi
-then
-echo `date`: module_federation_control - No MD5Checksum >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
-exit 101
-fi
-source /opt/karoshi/web_controls/checksums/admin_checksums/module_federation_control_cgi
-MD5SUM=`md5sum /var/www/cgi-bin_karoshi/admin/module_federation_control.cgi | cut -d' ' -f1`
-[ $MD5SUM'null' = null ] && MD5SUM=not_set
-if [ $MD5SUM'check' != $module_federation_control_cgi'check' ]
-then
-echo `date`: module_federation_control - Incorrect MD5Checksum >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
-exit 101
-fi
+
 
 ########################
 #Get variables
@@ -59,6 +44,7 @@ then
 echo `date`: module_federation_control - no data >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
 exit 101
 fi
+
 REMOTE_USER=`echo "$DATA" | cut -s -d: -f1`
 REMOTE_ADDR=`echo "$DATA" | cut -s -d: -f2`
 REMOTE_MD5=`echo "$DATA" | cut -s -d: -f3`
@@ -67,11 +53,7 @@ SERVERNAME=`echo "$DATA" | cut -s -d: -f4`
 ########################
 #Check data
 ########################
-if [ $REMOTE_MD5'check' != $MD5SUM'check' ]
-then
-echo `date`: module_federation_control - Not called by module_federation_control.cgi >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
-exit 101
-fi
+
 if [ $REMOTE_USER'null' = null ]
 then
 echo `date`: module_federation_control - Blank remote user >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
@@ -90,111 +72,59 @@ fi
 
 echo `date`: module_federation_control - Setting up $SERVERNAME by $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
 
-#Copy in module
-scp -p -r /opt/karoshi/serversetup/modules/ldap root@$SERVERNAME:/opt/karoshi/serversetup/modules/ 1> /dev/null
-
 #Copy in web management
-scp -p -r /opt/karoshi/serversetup/web_controls/ root@$SERVERNAME:/opt/karoshi/serversetup/ 1> /dev/null
-
-
-##########################
-#Configure ldap
-##########################
-#Copy in ldap module
-scp -p -r /opt/karoshi/serversetup/modules/ldap root@$SERVERNAME:/opt/karoshi/serversetup/modules/ 1> /dev/null
-scp -p -r /opt/karoshi/serversetup/distro/ubuntu/extra_server/software root@$SERVERNAME:/opt/karoshi/serversetup/distro/ubuntu/extra_server/ 1> /dev/null
-scp -p -r /opt/karoshi/serversetup/distro/pclinuxos/extra_server/software root@$SERVERNAME:/opt/karoshi/serversetup/distro/pclinuxos/extra_server/ 1> /dev/null
-#Transfer ldap information to the slave ldap server
-[ -f /opt/karoshi/.tempdata/users.ldif ] && rm -f /opt/karoshi/.tempdata/users.ldif
-[ -f /opt/karoshi/.tempdata/groups.ldif ] && rm -f /opt/karoshi/.tempdata/groups.ldif
-touch /opt/karoshi/.tempdata/users.ldif
-chown root.root /opt/karoshi/.tempdata/users.ldif
-chmod 0600 /opt/karoshi/.tempdata/users.ldif
-slapcat -s "ou=People,dc=karoshi,dc=local" -l /opt/karoshi/.tempdata/users.ldif
-slapcat -s "ou=Group,dc=karoshi,dc=local" -l /opt/karoshi/.tempdata/groups.ldif
-scp /opt/karoshi/.tempdata/users.ldif root@$SERVERNAME:"/opt/karoshi/.tempdata/"
-scp /opt/karoshi/.tempdata/groups.ldif root@$SERVERNAME:"/opt/karoshi/.tempdata/"
-scp /opt/karoshi/server_network/domain_information/domain_name root@$SERVERNAME:"/opt/karoshi/.tempdata/"
-rm -f /opt/karoshi/.tempdata/users.ldif
-rm -f /opt/karoshi/.tempdata/groups.ldif
-
-#ssh -x -o PasswordAuthentication=no $SERVERNAME '
-#mv /home/applications/profiles /home/applications/profiles.$$
-#mv /var/lib/samba/netlogon/windows_settings/security /var/lib/samba/netlogon/windows_settings/security.$$
-#mv /var/lib/samba/netlogon/windows_settings/drives /var/lib/samba/netlogon/windows_settings/drives.$$
-#'
-
-#Copy /home/applications/profiles to the federated server
-#scp -r /home/applications/profiles root@$SERVERNAME:"/home/applications/"
-#Copy /var/lib/samba/netlogon/windows_settings/security
-#scp -r /var/lib/samba/netlogon/windows_settings/security root@$SERVERNAME:"/var/lib/samba/netlogon/windows_settings/"
-#Copy /var/lib/samba/netlogon/windows_settings/drives
-#scp -r /var/lib/samba/netlogon/windows_settings/drives root@$SERVERNAME:"/var/lib/samba/netlogon/windows_settings/"
+#scp -p -r /opt/karoshi/serversetup/web_controls/ root@$SERVERNAME:/opt/karoshi/serversetup/ 1> /dev/null
 
 #Add flag files
 [ ! -d /opt/karoshi/server_network/federated_ldap_servers ] && mkdir -p /opt/karoshi/server_network/federated_ldap_servers
 mkdir -p /opt/karoshi/server_network/federated_ldap_servers/$SERVERNAME
 [ -d /opt/karoshi/server_network/servers/$SERVERNAME ] && rm -f -R  /opt/karoshi/server_network/servers/$SERVERNAME
 
+#Remove flag files in zones
+[ -f /opt/karoshi/server_network/zones/internal/servers/$SERVERNAME ] && rm -f  /opt/karoshi/server_network/zones/internal/servers/$SERVERNAME
+[ -f /opt/karoshi/server_network/zones/dmz/servers/$SERVERNAME ] && rm -f  /opt/karoshi/server_network/zones/dmz/servers/$SERVERNAME
+[ -f /opt/karoshi/server_network/zones/external/servers/$SERVERNAME ] && rm -f  /opt/karoshi/server_network/zones/external/servers/$SERVERNAME
+
 ############################
-#Make sure that there is a gap of $MACHINE_COUNT between the uidNumbers to allow for machine accounts to be added to the federated domains.
+#Create users on the federated server
 ############################
-MACHINE_COUNT=10000
-for FEDERATEDLDAPSERVERS in /opt/karoshi/server_network/federated_ldap_servers/*
+
+#Get list of users
+USERLIST=`getent passwd | grep /home/users | sed "s/ /SPACE/g"`
+ssh -x -o PasswordAuthentication=no $SERVERNAME '
+MD5SUM=`md5sum /var/www/cgi-bin_karoshi/admin/add_user.cgi | cut -d" " -f1`
+USERNAMESTYLE=userstyleS1
+for USERDATA in `echo -e "'$USERLIST'"`
 do
-FEDERATEDLDAPSERVER=`basename $FEDERATEDLDAPSERVERS`
+USERNAME=`echo $USERDATA | cut -d: -f1`
+NAMEDATA=`echo $USERDATA | cut -d: -f5 | sed "s/,//g;" | sed "s/SPACE/ /g"`
+FIRSTNAME=`echo $NAMEDATA | cut -d" " -f1`
+SURNAME=`echo $NAMEDATA | cut -d" " -f2`
+HOMEPATH=`echo $USERDATA | cut -d: -f6 | sed "s/$USERNAME//g"`
+GROUP=`basename $HOMEPATH`
+PASSWORD1=$RANDOM
+#Create user if it does not already exist
+getent passwd $USERNAME 1>/dev/null
 
-SAMBADOMAIN=`grep "workgroup ="  /etc/samba/smb.conf | cut -d= -f2 | sed 's/ //g'`
-LDAPPASS=`sed -n 1,1p /etc/ldap.secret`
-#Get uidnumber from this server
-UIDNUMBER=`ldapsearch -x -w $LDAPPASS -D "cn=admin,dc=karoshi,dc=local" sambaDomainName=$SAMBADOMAIN | grep ^uidNumber | cut -d: -f2 | sed 's/ //g' | tr -cd "0-9"`
-
-#Get uidnumber from federated server
-FEDERATEDUIDNUMBER=$(ssh -x -o PasswordAuthentication=no $FEDERATEDLDAPSERVER '
-SAMBADOMAIN=`grep "workgroup ="  /etc/samba/smb.conf | cut -d= -f2 | sed "s/ //g"`
-LDAPPASS=`sed -n 1,1p /etc/ldap.secret`
-ldapsearch -x -w $LDAPPASS -D "cn=admin,dc=karoshi,dc=local" sambaDomainName=$SAMBADOMAIN | grep ^uidNumber | cut -d: -f2 | sed "s/ //g" | tr -cd "0-9"
-')
-
-#Compare UID numbers and adjust if neccessary.
-let UID_DIFFERENCE=$UIDNUMBER-$FEDERATEDUIDNUMBER
-if [ $UID_DIFFERENCE -lt $MACHINE_COUNT ]
+if [ $? != 0 ]
 then
-let ADD_VALUE=$MACHINE_COUNT-$UID_DIFFERENCE
-let UIDNUMBER=$UIDNUMBER+$ADD_VALUE
-
-echo -e "dn: sambaDomainName=$SAMBADOMAIN,dc=karoshi,dc=local
-changetype: modify
-replace: uidNumber
-uidNumber: $UIDNUMBER
-" | ldapmodify -x -D "cn=admin,dc=karoshi,dc=local" -w $LDAPPASS 1>/dev/null
+echo "<li>"Creating User"</li>""<br>"Username: $USERNAME"<br>"Forename: $FORENAME"<br>"Surname: $SURNAME"<br>"Primary group: $PRIMARYGROUP"<br>"
+#Add user
+echo "'$REMOTE_USER':'$REMOTE_ADDR':$MD5SUM:$FIRSTNAME:$SURNAME:$USERNAME:$PASSWORD1:$GROUP:$USERNAMESTYLE:$ENROLLMENTNUMBER:$REQUESTFILE" | sudo -H /opt/karoshi/web_controls/exec/add_user
 fi
 done
-
-############################
-#Migrate user information on this server to users on the federated server
-############################
-SAMBADOMAIN=`grep "workgroup ="  /etc/samba/smb.conf | cut -d= -f2 | sed "s/ //g"`
-LDAPPASS=`sed -n 1,1p /etc/ldap.secret`
-MASTERSID=`ldapsearch -x -w $LDAPPASS -D "cn=admin,dc=karoshi,dc=local" sambaDomainName=$SAMBADOMAIN | grep ^sambaSID | cut -d: -f2 | sed "s/ //g"`
-
-SAMBASID=$(ssh -x -o PasswordAuthentication=no $SERVERNAME '
-LDAPPASS=`sed -n 1,1p /etc/ldap.secret`
-SAMBADOMAIN=`grep "workgroup ="  /etc/samba/smb.conf | cut -d= -f2 | sed "s/ //g"`
-ldapsearch -x -w $LDAPPASS -D "cn=admin,dc=karoshi,dc=local" sambaDomainName=$SAMBADOMAIN | grep ^sambaSID | cut -d: -f2 | sed "s/ //g"
-')
-
-ssh -x -o PasswordAuthentication=no $SERVERNAME '
-sed -i "s/'$MASTERSID'/'$SAMBASID'/g" /opt/karoshi/.tempdata/users.ldif
-sed -i "s/'$MASTERSID'/'$SAMBASID'/g" /opt/karoshi/.tempdata/groups.ldif
-/opt/karoshi/serversetup/modules/ldap/setupfederatedldapserver
 '
+
 ############################
 #Check if there are roaming profile users to sync
 ############################
 ROAMING_SYNC=yes
-[ ! -f /opt/karoshi/server_network/windows_roaming_profile_users ] && ROAMING_SYNC=no
+if [ ! -f /opt/karoshi/server_network/windows_roaming_profile_users ]
+then
+ROAMING_SYNC=no
+else
 [ `cat /opt/karoshi/server_network/windows_roaming_profile_users | wc -l` = 0 ] && ROAMING_SYNC=no
+fi
 
 if [ $ROAMING_SYNC = yes ]
 then
@@ -219,6 +149,7 @@ fi
 '
 done
 fi
+
 ############################
 #Modify web management menu
 ############################
@@ -265,6 +196,7 @@ done
 ########################
 #Copy any missing profiles to the federated server
 ########################
+echo "<li>"Copying any missing windows profiles"</li>"
 for WINPROFILES in /home/applications/profiles/*
 do
 WINPROFILE=`basename $WINPROFILES`
@@ -275,6 +207,7 @@ ssh -x -o PasswordAuthentication=no $SERVERNAME '
 '
 if [ `echo $?` = 105 ]
 then
+echo "<li>"Copying /home/applications/profiles/$WINPROFILE"<'/li>"
 scp -p -r /home/applications/profiles/$WINPROFILE/ root@$SERVERNAME:/home/applications/profiles/ 1> /dev/null
 ssh -x -o PasswordAuthentication=no $SERVERNAME '
 chown root.itadmin /home/applications/profiles/'$WINPROFILE'/
@@ -288,15 +221,15 @@ done
 #Add users to correct groups on federated servers
 ########################
 
-echo "<br><li>Adding users to correct groups on $SERVERNAME</li>"
-for EXISTING_USER in `getent passwd | grep /home/users/ | cut -d: -f1`
-do
-GROUPLIST=`groups $EXISTING_USER | cut -d: -f2 | sed "s/^ //g" | sed "s/ /,/g" | sed "s/Domain,Admins/Domain Admins/g"`
-echo Adding $EXISTING_USER to $GROUPLIST on $SERVERNAME"<br>"
-ssh -o PasswordAuthentication=no -o ConnectTimeout=3 $SERVERNAME '
-smbldap-usermod -G "'$GROUPLIST'" '$EXISTING_USER'
-'
-done
+#echo "<br><li>Adding users to correct groups on $SERVERNAME</li>"
+#for EXISTING_USER in `getent passwd | grep /home/users/ | cut -d: -f1`
+#do
+#GROUPLIST=`groups $EXISTING_USER | cut -d: -f2 | sed "s/^ //g" | sed "s/ /,/g" | sed "s/Domain,Admins/Domain Admins/g"`
+#echo Adding $EXISTING_USER to $GROUPLIST on $SERVERNAME"<br>"
+#ssh -o PasswordAuthentication=no -o ConnectTimeout=3 $SERVERNAME '
+#smbldap-usermod -G "'$GROUPLIST'" '$EXISTING_USER'
+#'
+#done
 
 /opt/karoshi/serversetup/all/"useful scripts"/refreshcronjobs
 ############################
diff --git a/serversetup/web_controls/scripts/exec/pdc/module_smbwebclient b/serversetup/web_controls/scripts/exec/pdc/module_smbwebclient
--- a/serversetup/web_controls/scripts/exec/pdc/module_smbwebclient
+++ b/serversetup/web_controls/scripts/exec/pdc/module_smbwebclient
@@ -63,6 +63,7 @@ REMOTE_USER=`echo "$DATA" | cut -s -d: -f1`
 REMOTE_ADDR=`echo "$DATA" | cut -s -d: -f2`
 REMOTE_MD5=`echo "$DATA" | cut -s -d: -f3`
 SERVERNAME=`echo "$DATA" | cut -s -d: -f4`
+ALIAS=`echo "$DATA" | cut -s -d: -f5`
 
 ########################
 #Check data
@@ -89,59 +90,92 @@ exit 101
 fi
 if [ $SERVERNAME'null' = null ]
 then
-echo `date`: module_fileserver - Blank servername by $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
+echo `date`: module_smbwebclient - Blank servername by $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
 exit 101
 fi
+if [ $ALIAS'null' = null ]
+then
+echo `date`: module_smbwebclient - Blank alias by $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
+exit
+fi
+
 echo `date`: setupsmbwebclient on $SERVERNAME by $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
 
-SAMBA_DOMAIN=`grep "workgroup =" /etc/samba/smb.conf | cut -d' ' -f3 | sed -n 1,1p`
+source /opt/karoshi/serversetup/variables/distro
 
+#Check that this server has been setup with the correct authentication
+echo "$REMOTE_USER:$REMOTE_ADDR:$MD5SUM:$SERVERNAME:users:" | /opt/karoshi/serversetup/modules/authentication/check_auth
+if [ $? = 101 ]
+then
+echo $AUTHENTICATIONFAILMSG"<br><br>"
+echo `date`: module_smbwebclient - $SERVERNAME does not have the correct authentication "for" this module by $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
+sleep 2
+exit 101
+fi
+
+#Add entry to samba4 dns
+LDAPPASS=`sed -n 1,1p /etc/ldap.secret`
+SERVERIP=`net lookup $SERVERNAME`
+source /opt/karoshi/server_network/domain_information/domain_name
+echo `date`: module_smbwebclient - checking "if" $ALIAS.$REALM is "in" the dns records by $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
+samba-tool dns query 127.0.0.1 $REALM $ALIAS.$REALM CNAME --username=Administrator --password=$LDAPPASS 1>> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE 2>> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
+if [ `echo $?` != 0 ]
+then
+echo `date`: dnsadd - adding $DOMAINPATH $SERVERIP to the dns records by $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
+samba-tool dns add 127.0.0.1 $REALM $ALIAS CNAME $SERVERNAME.$REALM --username=Administrator --password=$LDAPPASS 1>> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE 2>> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
+fi
+
+if [ ! -f /etc/ssl/apache/$ALIAS.$REALM.key ]
+then
+echo "$REMOTE_USER:$REMOTE_ADDR:$SERVERNAME:$ALIAS.$REALM:" | /opt/karoshi/serversetup/distro/$DISTROCHOICE/scripts/apachesslcert
+[ `echo $?` != 0 ] && exit 101 
+fi
 
 if [ $SERVERNAME = $HOSTNAME ]
 then
 #Install smbwebclient
-echo $REMOTE_USER:$REMOTE_ADDR:$MD5SUM:$HOSTNAME:$PDCIP:$SAMBA_DOMAIN: | /opt/karoshi/serversetup/modules/smbwebclient/setup_smbwebclient
-fi
-
-
-
-if [ $SERVERNAME != $HOSTNAME ]
-then
-
-#Configure ldap
-if [ ! -f /opt/karoshi/server_network/slave_ldap_servers/$SERVERNAME ]
-then
-if [ ! -f /opt/karoshi/server_network/ldap_clients/$SERVERNAME ]
-then
-PDCIP=`net lookup $HOSTNAME`
-ssh -x -o PasswordAuthentication=no $SERVERNAME '
-echo "'$REMOTE_USER':'$REMOTE_ADDR':'$MD5SUM':'$HOSTNAME':'$PDCIP':" | /opt/karoshi/serversetup/modules/ldap/configureldap
-'
-#Copy in /etc/ldap.secret
-scp -p /etc/ldap.secret root@$SERVERNAME:/etc/ 1> /dev/null
-[ ! -d /opt/karoshi/server_network/ldap_clients/ ] && mkdir -p /opt/karoshi/server_network/ldap_clients/
-touch /opt/karoshi/server_network/ldap_clients/$SERVERNAME
-fi
-fi
-
+echo $REMOTE_USER:$REMOTE_ADDR:$MD5SUM:$HOSTNAME:$ALIAS.$REALM: | /opt/karoshi/serversetup/modules/smbwebclient/setup_smbwebclient
+else
 
 ssh -x -o PasswordAuthentication=no $SERVERNAME '
-
 [ ! -d /opt/karoshi/serversetup/language/'$LANGCHOICE'/modules ] && mkdir -p /opt/karoshi/serversetup/language/'$LANGCHOICE'/modules
 [ ! -d /opt/karoshi/serversetup/modules/ ] && mkdir -p /opt/karoshi/serversetup/modules/
 '
+#Update alias entry for the server
+[ ! -d /opt/karoshi/server_network/aliases ] && mkdir -p /opt/karoshi/server_network/aliases
+[ ! -f /opt/karoshi/server_network/aliases/$SERVERNAME ] && echo $ALIAS > /opt/karoshi/server_network/aliases/$SERVERNAME
 
 #Copy in language files
 scp -p -r /opt/karoshi/serversetup/language/$LANGCHOICE/modules/smbwebclient root@$SERVERNAME:/opt/karoshi/serversetup/language/$LANGCHOICE/modules/ 1> /dev/null
 #Copy in module
 scp -p -r /opt/karoshi/serversetup/modules/smbwebclient root@$SERVERNAME:/opt/karoshi/serversetup/modules/ 1> /dev/null
+#Copy in realm information
+scp -p -r /opt/karoshi/server_network/domain_information root@$SERVERNAME:/opt/karoshi/server_network/ 1> /dev/null
 #Install smbwebclient
 PDCIP=`net lookup $HOSTNAME`
-SAMBA_DOMAIN=`grep "workgroup =" /etc/samba/smb.conf | cut -d' ' -f3 | sed -n 1,1p`
+
+#Check that we can ping the pdc
+ssh -x -o PasswordAuthentication=no $SERVERNAME '
+#Check to see that we can ping the PDC
+ping -c 2 '$PDCIP' 1>/dev/null
+if [  echo $? != 0 ]
+then
+echo `date` : setupfileserver - '$PINGFAIL'."<br>"
+exit 101
+fi
+fi
+
+'
+if [ $? = 101 ]
+then
+echo `date`: module_smbwebclient - cannot ping $PDCIP by $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
+fi
+
 ssh -x -o PasswordAuthentication=no $SERVERNAME '
 [ ! -d /opt/karoshi/server_network/ ] && mkdir -p /opt/karoshi/server_network/
-echo '$REMOTE_USER:$REMOTE_ADDR:$MD5SUM:$HOSTNAME:$PDCIP:$SAMBA_DOMAIN' | /opt/karoshi/serversetup/modules/smbwebclient/setup_smbwebclient
+echo '$REMOTE_USER:$REMOTE_ADDR:$MD5SUM:$HOSTNAME:$ALIAS.$REALM' | /opt/karoshi/serversetup/modules/smbwebclient/setup_smbwebclient
 '
+
 #Copy group information to the home access server
 scp -p -r /opt/karoshi/server_network/group_information root@$SERVERNAME:/opt/karoshi/server_network/ 1> /dev/null
 fi
@@ -150,9 +184,7 @@ fi
 [ ! -d /opt/karoshi/modules/smbwebclient ] && mkdir -p /opt/karoshi/modules/smbwebclient
 #echo '<a href="http://www.smbwebclient.com/" target="_blank"><img style="border: 0px solid ;" alt="" src="/images/help/info.png"></a>' > /opt/karoshi/modules/smbwebclient/weblink
 echo '<b>'Server'</b>': $SERVERNAME > /opt/karoshi/modules/smbwebclient/installed_information
-echo '<b>'Access'</b>': '<a href="https://'$SERVERNAME':50000" target="_blank">https://'$SERVERNAME':50000</a>' >> /opt/karoshi/modules/smbwebclient/installed_information
-
-
+echo '<b>'Access'</b>': '<a href="https://'$ALIAS.$REALM':50000/smbwebclient" target="_blank">https://'$ALIAS.$REALM':50000/smbwebclient</a>' >> /opt/karoshi/modules/smbwebclient/installed_information
 
 ########################
 #Language
@@ -168,7 +200,7 @@ source /opt/karoshi/web_controls/language/$LANGCHOICE/all
 #Add role information
 [ ! -d /opt/karoshi/server_network/servers/$SERVERNAME ] && mkdir -p /opt/karoshi/server_network/servers/$SERVERNAME
 echo $ROLE"<br>" > /opt/karoshi/server_network/servers/$SERVERNAME/homeaccess
-echo '<a href="https://'$SERVERNAME':50000" target="_blank">https://'$SERVERNAME':50000</a><br>' >> /opt/karoshi/server_network/servers/$SERVERNAME/homeaccess
+echo '<a href="https://'$ALIAS.$REALM':50000/smbwebclient" target="_blank">https://'$ALIAS.$REALM':50000/smbwebclient</a><br>' >> /opt/karoshi/server_network/servers/$SERVERNAME/homeaccess
 #echo $ROLE2"<br>" > /opt/karoshi/server_network/servers/$SERVERNAME/apacheserver
 [ -f /opt/karoshi/server_network/servers/$SERVERNAME/no_role ] && rm -f /opt/karoshi/server_network/servers/$SERVERNAME/no_role
 [ ! -d /opt/karoshi/server_network/webservers/ ] && mkdir -p /opt/karoshi/server_network/webservers
