buildserver - bugfixes for openvpn, revised theme for karoshi user.

diff --git a/serversetup/web_controls/scripts/exec/pdc/karoshi_servers_add b/serversetup/web_controls/scripts/exec/pdc/karoshi_servers_add
--- a/serversetup/web_controls/scripts/exec/pdc/karoshi_servers_add
+++ b/serversetup/web_controls/scripts/exec/pdc/karoshi_servers_add
@@ -222,7 +222,7 @@ fi
 echo "cat /etc/hostname-fqdn" > /bin/hostname-fqdn
 chmod 0755 /bin/hostname-fqdn
 ' 1>/dev/null 2>> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
-SSHRESULT=`echo $?`
+SSHRESULT=$?
 
 function remove_dns_entry {
 #Remove entry from dns
@@ -234,7 +234,7 @@ exit 101
 if [ $SSHRESULT = 102 ]
 then
 #Server name does not match
-echo "<li>$SERVER - this name does not match the hostname of the server you are connecting to</li>"
+echo "<li>$SERVER - this name does not match the hostname of the server you are connecting to.</li>"
 echo `date`: karoshi_servers_add - $SERVER name mismatch with remote server by $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
 sleep 3
 exit 101
@@ -258,11 +258,13 @@ sleep 3
 exit 101
 fi
 
-#if [ $SSHRESULT != 0 ]
-#then
-#remove_dns_entry
-#exit 101
-#fi
+if [ $SSHRESULT != 0 ]
+then
+echo "<li>$SERVER - SSH connection failure</li>"
+echo `date`: karoshi_servers_add - $SERVER: $ZONE SSH connection failure by $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
+sleep 3
+exit 101
+fi
 
 #Check to see if the server is in a different domain.
 echo `date`: karoshi_servers_add - checking that $SERVER is "in" the same domain by $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
@@ -282,7 +284,7 @@ then
 if [ "$REALM2" != "$REALM" ]
 then
 REALM=$REALM2
-#Make sure that authtype is set to none if this is the case since cannot different realms together at this point.
+#Make sure that authtype is set to none if this is the case since cannot different realms cannot join together at this point.
 if [ $AUTHENTICATION != none ]
 then
 echo "<li>$SERVER - this server is in the wrong domain for this authentication type.</li>"
@@ -353,9 +355,8 @@ LDAPPASS=`sed -n 1,1p /etc/ldap.secret`
 
 echo `date`: karoshi_servers_add - checking "if" $SERVER is "in" the dns records by $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
 samba-tool dns query 127.0.0.1 $REALM $SERVER A --username=Administrator --password=$LDAPPASS 1>> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE 2>> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
-if [ `echo $?` != 0 ]
+if [ $? != 0 ]
 then
-
 #Create zone if it does not exist
 echo `date`: karoshi_servers_add - checking "if" zone $REALM is "in" the dns records by $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
 samba-tool dns zoneinfo 127.0.0.1 $REALM --username=Administrator --password=$LDAPPASS 1>/dev/null 2>> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
