Locale Language Support
All scripts modified to use locale language support instead of sourcing language files.

diff --git a/serversetup/web_controls/scripts/exec/pdc/module_reverse_proxy b/serversetup/web_controls/scripts/exec/pdc/module_reverse_proxy
--- a/serversetup/web_controls/scripts/exec/pdc/module_reverse_proxy
+++ b/serversetup/web_controls/scripts/exec/pdc/module_reverse_proxy
@@ -29,16 +29,16 @@ LOG_DATE=`date +%F`
 ########################
 if ! test -f /opt/karoshi/web_controls/checksums/admin_checksums/module_reverse_proxy_cgi
 then
-echo `date`: module_reverse_proxy - No admin MD5Checksum >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
-exit 101
+	echo `date`: module_reverse_proxy - No admin MD5Checksum >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
+	exit 101
 fi
 source /opt/karoshi/web_controls/checksums/admin_checksums/module_reverse_proxy_cgi
 MD5SUM=`md5sum /var/www/cgi-bin_karoshi/admin/module_reverse_proxy.cgi | cut -d' ' -f1`
-[ $MD5SUM'null' = null ] && MD5SUM=not_set
+[ -z "$MD5SUM" ] && MD5SUM=not_set
 if [ $MD5SUM'check' != $module_reverse_proxy_cgi'check' ]
 then
-echo `date`: module_reverse_proxy - Incorrect admin MD5Checksum >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
-exit 101
+	echo `date`: module_reverse_proxy - Incorrect admin MD5Checksum >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
+	exit 101
 fi
 
 ########################
@@ -47,16 +47,16 @@ fi
 numArgs=$#
 if [ $numArgs != 0 ]
 then
-echo `date`: module_reverse_proxy - incorrect number of arguments >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
-exit 101
+	echo `date`: module_reverse_proxy - incorrect number of arguments >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
+	exit 101
 fi
 
 read DATA
 DATA=`echo $DATA | tr -cd 'A-Za-z0-9\._:\-%'`
-if [ $DATA'null' = null ]
+if [ -z "$DATA" ]
 then
-echo `date`: module_reverse_proxy - no data >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
-exit 101
+	echo `date`: module_reverse_proxy - no data >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
+	exit 101
 fi
 REMOTE_USER=`echo "$DATA" | cut -s -d: -f1`
 REMOTE_ADDR=`echo "$DATA" | cut -s -d: -f2`
@@ -68,35 +68,33 @@ ALIAS=`echo "$DATA" | cut -s -d: -f5 | sed 's/%3A/:/g' | sed 's/%2F/\//g'`
 ########################
 if [ $REMOTE_MD5'check' != $MD5SUM'check' ]
 then
-echo `date`: module_reverse_proxy - Not called by module_reverse_proxy.cgi >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
-exit 101
+	echo `date`: module_reverse_proxy - Not called by module_reverse_proxy.cgi >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
+	exit 101
 fi
-if [ $REMOTE_USER'null' = null ]
+if [ -z "$REMOTE_USER" ]
 then
-echo `date`: module_reverse_proxy - Blank remote user >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
-exit 101
+	echo `date`: module_reverse_proxy - Blank remote user >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
+	exit 101
 fi
-if [ $REMOTE_ADDR'null' = null ]
+if [ -z "$REMOTE_ADDR" ]
 then
-echo `date`: module_reverse_proxy - Blank remote tcpip address >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
-exit 101
+	echo `date`: module_reverse_proxy - Blank remote tcpip address >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
+	exit 101
 fi
-if [ $WEBSERVER'null' = null ]
+if [ -z "$WEBSERVER" ]
 then
-echo `date`: module_reverse_proxy - Blank server by $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
-exit 101
+	echo `date`: module_reverse_proxy - Blank server by $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
+	exit 101
 fi
 if [ `grep -c ^$REMOTE_USER: /opt/karoshi/web_controls/web_access_admin` != 1 ]
 then
-echo `date`: module_reverse_proxy - access denied to $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
-exit 101
+	echo `date`: module_reverse_proxy - access denied to $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
+	exit 101
 fi
 echo `date`: setupmoodle by $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
 
 [ -f /opt/karoshi/web_controls/user_prefs/$REMOTE_USER ] && source /opt/karoshi/web_controls/user_prefs/$REMOTE_USER
-[ -f /opt/karoshi/web_controls/language/$LANGCHOICE/modules/reverseproxy/setupreverseproxy ] || LANGCHOICE=englishuk
-source /opt/karoshi/serversetup/language/$LANGCHOICE/modules/reverseproxy/setupreverseproxy
-
+TEXTDOMAIN=karoshi-server
 
 source /opt/karoshi/serversetup/variables/distro
 source /opt/karoshi/serversetup/distro/$DISTROCHOICE/all/software
@@ -118,9 +116,9 @@ fi
 
 if [ $WEBSERVER = `hostname-fqdn` ]
 then
-echo "<li>"$ERRORMSG2"</li>"
-echo `date`: module_reverse_proxy not allowed to set this up on $HOSTNNAME by $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
-exit 101
+	echo '<li>'$"You cannot setup a reverse proxy on the main server."'</li>'
+	echo `date`: module_reverse_proxy not allowed to set this up on $HOSTNNAME by $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
+	exit 101
 fi
 
 #Copy in language files
@@ -155,31 +153,31 @@ MODCHECK2=`grep -c -w 443 /etc/shorewall/rules`
 MOD_SHOREWALL=no
 if [ $MODCHECK = 0 ]
 then
-MOD_SHOREWALL=yes
-PORTS="80"
+	MOD_SHOREWALL=yes
+	PORTS="80"
 fi
 
 if [ $MODCHECK2 = 0 ]
 then
-MOD_SHOREWALL=yes
-PORTS="443"
+	MOD_SHOREWALL=yes
+	PORTS="443"
 fi
 
 if [ $MODCHECK = 0 ] && [ $MODCHECK2 = 0 ]
 then
-MOD_SHOREWALL=yes
-PORTS="80,443"
+	MOD_SHOREWALL=yes
+	PORTS="80,443"
 fi
 
 if [ $MOD_SHOREWALL = yes ]
 then
-echo "<br>"'$SHOREWALLMSG'
-LINENUM=`grep -n "LAST LINE -- ADD YOUR ENTRIES BEFORE THIS ONE -- DO NOT REMOVE" /etc/shorewall/rules | cut -d: -f1`
-sed -i $LINENUM"c"\ACCEPT"	"net"	"fw"	"tcp"	"$PORTS"	"-"#"apacherule /etc/shorewall/rules
-echo "#"LAST LINE -- ADD YOUR ENTRIES BEFORE THIS ONE -- DO NOT REMOVE >> /etc/shorewall/rules
-echo "<br>"'$RESTARTSWMSG'
-/opt/karoshi/serversetup/distro/$DISTROCHOICE/scripts/control_services/shorewall_stop 1>/dev/null
-/opt/karoshi/serversetup/distro/$DISTROCHOICE/scripts/control_services/shorewall_start 1>/dev/null
+	echo "<br>"'$"Modifying shorewall rules to allow ports 80 and 443."'
+	LINENUM=`grep -n "LAST LINE -- ADD YOUR ENTRIES BEFORE THIS ONE -- DO NOT REMOVE" /etc/shorewall/rules | cut -d: -f1`
+	sed -i $LINENUM"c"\ACCEPT"	"net"	"fw"	"tcp"	"$PORTS"	"-"#"apacherule /etc/shorewall/rules
+	echo "#"LAST LINE -- ADD YOUR ENTRIES BEFORE THIS ONE -- DO NOT REMOVE >> /etc/shorewall/rules
+	echo "<br>"'$"Restarting shorewall"'
+	/opt/karoshi/serversetup/distro/$DISTROCHOICE/scripts/control_services/shorewall_stop 1>/dev/null
+	/opt/karoshi/serversetup/distro/$DISTROCHOICE/scripts/control_services/shorewall_start 1>/dev/null
 fi
 
 #Copy in config files
@@ -203,7 +201,7 @@ source /opt/karoshi/serversetup/variables/distro
 ##########################
 #Install nginx
 ##########################
-echo "<li>"'$INSTALLMSG'"</li><br>"
+echo "<li>"'$"Checking for modules"'"</li><br>"
 /opt/karoshi/serversetup/distro/$DISTROCHOICE/modules/reverseproxy/software
 
 ###########################
@@ -226,29 +224,29 @@ touch /etc/nginx/proxysites
 ###########################
 #Show completed message
 ###########################
-echo "<br><li>'$COMPLETEDMSG'</li><br>"
+echo "<br><li>'$"Setup Reverse Proxy Completed"'</li><br>"
 '
 
 #Add in any existing reverse proxy rules
 if [ -d /opt/karoshi/server_network/reverseproxy/sites ]
 then
-if [ `ls -1 /opt/karoshi/server_network/reverseproxy/sites | wc -l` -gt 0 ]
-then
-cat /opt/karoshi/server_network/reverseproxy/sites/* > /opt/karoshi/server_network/reverseproxy/proxysites
-#Copy proxysites to /etc/nginx
-scp /opt/karoshi/server_network/reverseproxy/proxysites root@$WEBSERVER:"/etc/nginx/"
-ssh -x -o PasswordAuthentication=no $WEBSERVER '
-#Reload nginx
-source /opt/karoshi/serversetup/variables/distro
-/opt/karoshi/serversetup/distro/$DISTROCHOICE/scripts/control_services/nginx_reload
-'
-fi
+	if [ `ls -1 /opt/karoshi/server_network/reverseproxy/sites | wc -l` -gt 0 ]
+	then
+		cat /opt/karoshi/server_network/reverseproxy/sites/* > /opt/karoshi/server_network/reverseproxy/proxysites
+		#Copy proxysites to /etc/nginx
+		scp /opt/karoshi/server_network/reverseproxy/proxysites root@$WEBSERVER:"/etc/nginx/"
+		ssh -x -o PasswordAuthentication=no $WEBSERVER '
+		#Reload nginx
+		source /opt/karoshi/serversetup/variables/distro
+		/opt/karoshi/serversetup/distro/$DISTROCHOICE/scripts/control_services/nginx_reload
+		'
+	fi
 fi
 
 #########################
 #Add role information
 #########################
-echo $ROLE"<br>" > /opt/karoshi/server_network/servers/$WEBSERVER/reverseproxyserver
+echo $"Reverse Proxy Server""<br>" > /opt/karoshi/server_network/servers/$WEBSERVER/reverseproxyserver
 [ -f /opt/karoshi/server_network/servers/$WEBSERVER/no_role ] && rm -f /opt/karoshi/server_network/servers/$WEBSERVER/no_role
 echo $WEBSERVER > /opt/karoshi/server_network/reverseproxyserver
 sed -i 's/REVERSEPROXYCTRL=no/REVERSEPROXYCTRL=yes/g' /opt/karoshi/server_network/menusettings
diff --git a/serversetup/web_controls/scripts/exec/pdc/module_squid b/serversetup/web_controls/scripts/exec/pdc/module_squid
--- a/serversetup/web_controls/scripts/exec/pdc/module_squid
+++ b/serversetup/web_controls/scripts/exec/pdc/module_squid
@@ -24,22 +24,22 @@
 #
 #Website: http://www.karoshi.org.uk
 LOG_DATE=`date +%F`
-[ $LOG_DATE'null' = null ] && exit
+[ -z "$LOG_DATE" ] && exit
 ########################
 #Check md5checksum
 ########################
 if ! test -f /opt/karoshi/web_controls/checksums/admin_checksums/module_squid_cgi
 then
-echo `date`: module_squid - No MD5Checksum >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
-exit 101
+	echo `date`: module_squid - No MD5Checksum >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
+	exit 101
 fi
 source /opt/karoshi/web_controls/checksums/admin_checksums/module_squid_cgi
 MD5SUM=`md5sum /var/www/cgi-bin_karoshi/admin/module_squid.cgi | cut -d' ' -f1`
-[ $MD5SUM'null' = null ] && MD5SUM=not_set
+[ -z "$MD5SUM" ] && MD5SUM=not_set
 if [ $MD5SUM'check' != $module_squid_cgi'check' ]
 then
-echo `date`: module_squid - Incorrect MD5Checksum >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
-exit 101
+	echo `date`: module_squid - Incorrect MD5Checksum >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
+	exit 101
 fi
 
 ########################
@@ -48,13 +48,13 @@ fi
 numArgs=$#
 if [ $numArgs != 0 ]
 then
-echo `date`: module_squid - incorrect number of arguments >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
-exit 101
+	echo `date`: module_squid - incorrect number of arguments >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
+	exit 101
 fi
 
 read DATA
 DATA=`echo $DATA | tr -cd 'A-Za-z0-9\._:%\n-+-'`
-if [ $DATA'null' = null ]
+if [ -z "$DATA" ]
 then
 echo `date`: module_squid - no data >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
 exit 101
@@ -68,23 +68,23 @@ SERVERNAME=`echo "$DATA" | cut -s -d: -f4`
 ########################
 if [ $REMOTE_MD5'check' != $MD5SUM'check' ]
 then
-echo `date`: module_squid - Not called by module_squid.cgi >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
-exit 101
+	echo `date`: module_squid - Not called by module_squid.cgi >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
+	exit 101
 fi
 if [ -z "$REMOTE_USER" ]
 then
-echo `date`: module_squid - Blank remote user >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
-exit 101
+	echo `date`: module_squid - Blank remote user >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
+	exit 101
 fi
 if [ -z "$REMOTE_ADDR" ]
 then
-echo `date`: module_squid - Blank remote tcpip address >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
-exit 101
+	echo `date`: module_squid - Blank remote tcpip address >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
+	exit 101
 fi
 if [ -z "$SERVERNAME" ]
 then
-echo `date`: module_squid - Blank servername by $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
-exit 101
+	echo `date`: module_squid - Blank servername by $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
+	exit 101
 fi
 
 echo `date`: module_squid - Setting up $SERVERNAME by $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
@@ -92,13 +92,13 @@ echo `date`: module_squid - Setting up $SERVERNAME by $REMOTE_USER from $REMOTE_
 ########################
 #Language
 ########################
-LANGCHOICE=englishuk
+
 STYLESHEET=defaultstyle.css
 [ -f /opt/karoshi/web_controls/user_prefs/$REMOTE_USER ] && source /opt/karoshi/web_controls/user_prefs/$REMOTE_USER
-[ -f /opt/karoshi/serversetup/language/$LANGCHOICE/modules/squid/setupsquid ] || LANGCHOICE=englishuk
+TEXTDOMAIN=karoshi-server
+
+[ -f /opt/karoshi/serversetup/language/$LANGCHOICE/modules/squid/setupsquid ] || 
 source /opt/karoshi/serversetup/language/$LANGCHOICE/modules/squid/setupsquid
-[ -f /opt/karoshi/web_controls/language/$LANGCHOICE/all ] || LANGCHOICE=englishuk
-source /opt/karoshi/web_controls/language/$LANGCHOICE/all
 
 source /opt/karoshi/server_network/domain_information/domain_name
 
@@ -109,44 +109,44 @@ PDCIP=`net lookup $HOSTNAME`
 LDAPSTATUS=notset
 if [ $SERVERNAME != `hostname-fqdn` ]
 then
-PDCIP=`net lookup $HOSTNAME`
-#Get samba 4 database password
-LDAPPASS=`sed -n 1,1p /etc/ldap.secret`
+	PDCIP=`net lookup $HOSTNAME`
+	#Get samba 4 database password
+	LDAPPASS=`sed -n 1,1p /etc/ldap.secret`
 
-#Check that this server has been setup with the correct authentication
-echo "$REMOTE_USER:$REMOTE_ADDR:$MD5SUM:$SERVERNAME:users:" | /opt/karoshi/serversetup/modules/authentication/check_auth
-if [ $? = 101 ]
-then
-echo $AUTHENTICATIONFAILMSG"<br><br>"
-echo `date`: module_squid - $SERVERNAME does not have the correct authentication "for" this module by $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
-exit 101
-fi
+	#Check that this server has been setup with the correct authentication
+	echo "$REMOTE_USER:$REMOTE_ADDR:$MD5SUM:$SERVERNAME:users:" | /opt/karoshi/serversetup/modules/authentication/check_auth
+	if [ $? = 101 ]
+	then
+		echo $"This server does not have the correct authentication set up on it.""<br><br>"
+		echo `date`: module_squid - $SERVERNAME does not have the correct authentication "for" this module by $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
+		exit 101
+	fi
 
-#Copy in language files
-scp -p -r /opt/karoshi/serversetup/language/$LANGCHOICE/modules/squid root@$SERVERNAME:/opt/karoshi/serversetup/language/$LANGCHOICE/modules/ 1> /dev/null
-#Copy in module
-scp -p -r /opt/karoshi/serversetup/modules/squid root@$SERVERNAME:/opt/karoshi/serversetup/modules/ 1> /dev/null
-#Copy in fail2ban files
-#scp -p -r /opt/karoshi/serversetup/all/fail2ban root@$SERVERNAME:/opt/karoshi/serversetup/all/ 1> /dev/null
+	#Copy in language files
+	scp -p -r /opt/karoshi/serversetup/language/$LANGCHOICE/modules/squid root@$SERVERNAME:/opt/karoshi/serversetup/language/$LANGCHOICE/modules/ 1> /dev/null
+	#Copy in module
+	scp -p -r /opt/karoshi/serversetup/modules/squid root@$SERVERNAME:/opt/karoshi/serversetup/modules/ 1> /dev/null
+	#Copy in fail2ban files
+	#scp -p -r /opt/karoshi/serversetup/all/fail2ban root@$SERVERNAME:/opt/karoshi/serversetup/all/ 1> /dev/null
 
-#########################
-#Run module
-#########################
+	#########################
+	#Run module
+	#########################
 
-ssh -x -o PasswordAuthentication=no $SERVERNAME '
-echo '$REMOTE_USER:$REMOTE_ADDR:$MD5SUM:$HOSTNAME:$PDCIP:$AUTHTYPE:$PASSWORD:' | /opt/karoshi/serversetup/modules/squid/setupsquid
-'
-[ $? = 101 ] && exit 101
+	ssh -x -o PasswordAuthentication=no $SERVERNAME '
+	echo '$REMOTE_USER:$REMOTE_ADDR:$MD5SUM:$HOSTNAME:$PDCIP:$AUTHTYPE:$PASSWORD:' | /opt/karoshi/serversetup/modules/squid/setupsquid
+	'
+	[ $? = 101 ] && exit 101
 
-else
-echo $REMOTE_USER:$REMOTE_ADDR:$MD5SUM:$HOSTNAME:$PDCIP:$AUTHTYPE:$PASSWORD: | /opt/karoshi/serversetup/modules/squid/setupsquid
-[ $? = 101 ] && exit 101
+	else
+		echo $REMOTE_USER:$REMOTE_ADDR:$MD5SUM:$HOSTNAME:$PDCIP:$AUTHTYPE:$PASSWORD: | /opt/karoshi/serversetup/modules/squid/setupsquid
+	[ $? = 101 ] && exit 101
 fi
 
 #Add role information
 [ ! -d /opt/karoshi/server_network/servers/$SERVERNAME ] && mkdir -p /opt/karoshi/server_network/servers/$SERVERNAME
-echo $ROLE"<br>" > /opt/karoshi/server_network/servers/$SERVERNAME/squid
-echo $ROLE3"<br>" > /opt/karoshi/server_network/servers/$SERVERNAME/apt-cacher-ng
+echo $"Squid Internet Proxy - port 3128""<br>" > /opt/karoshi/server_network/servers/$SERVERNAME/squid
+echo $"Apt Proxy - port 3142""<br>" > /opt/karoshi/server_network/servers/$SERVERNAME/apt-cacher-ng
 sed -i 's/INTERNETCTRL=no/INTERNETCTRL=yes/g' /opt/karoshi/server_network/menusettings
 [ -f /opt/karoshi/server_network/servers/$SERVERNAME/no_role ] && rm -f /opt/karoshi/server_network/servers/$SERVERNAME/no_role
 echo $SERVERNAME > /opt/karoshi/server_network/proxyserver
diff --git a/serversetup/web_controls/scripts/exec/pdc/zfs_raid_control b/serversetup/web_controls/scripts/exec/pdc/zfs_raid_control
--- a/serversetup/web_controls/scripts/exec/pdc/zfs_raid_control
+++ b/serversetup/web_controls/scripts/exec/pdc/zfs_raid_control
@@ -34,11 +34,11 @@ exit 101
 fi
 source /opt/karoshi/web_controls/checksums/admin_checksums/zfs_raid_control_cgi
 MD5SUM=`md5sum /var/www/cgi-bin_karoshi/admin/zfs_raid_control.cgi | cut -d' ' -f1`
-[ $MD5SUM'null' = null ] && MD5SUM=not_set
+[ -z "$MD5SUM" ] && MD5SUM=not_set
 if [ $MD5SUM'check' != $zfs_raid_control_cgi'check' ]
 then
-echo `date`: zfs_raid_control - Incorrect admin MD5Checksum >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
-exit 101
+	echo `date`: zfs_raid_control - Incorrect admin MD5Checksum >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
+	exit 101
 fi
 
 ########################
@@ -47,16 +47,16 @@ fi
 numArgs=$#
 if [ $numArgs != 0 ]
 then
-echo `date`: zfs_raid_control - incorrect number of arguments >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
-exit 101
+	echo `date`: zfs_raid_control - incorrect number of arguments >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
+	exit 101
 fi
 
 read DATA
 DATA=`echo $DATA | tr -cd 'A-Za-z0-9\._:\-'`
-if [ $DATA'null' = null ]
+if [ -z "$DATA" ]
 then
-echo `date`: zfs_raid_control - no data >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
-exit 101
+	echo `date`: zfs_raid_control - no data >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
+	exit 101
 fi
 REMOTE_USER=`echo "$DATA" | cut -s -d: -f1`
 REMOTE_ADDR=`echo "$DATA" | cut -s -d: -f2`
@@ -69,58 +69,54 @@ SERVERMASTER=`echo "$DATA" | cut -s -d: -f6`
 ########################
 if [ $REMOTE_MD5'check' != $MD5SUM'check' ]
 then
-echo `date`: zfs_raid_control - Not called by zfs_raid_control.cgi >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
-exit 101
+	echo `date`: zfs_raid_control - Not called by zfs_raid_control.cgi >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
+	exit 101
 fi
-if [ $REMOTE_USER'null' = null ]
+if [ -z "$REMOTE_USER" ]
 then
-echo `date`: zfs_raid_control - Blank remote user >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
-exit 101
+	echo `date`: zfs_raid_control - Blank remote user >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
+	exit 101
 fi
-if [ $REMOTE_ADDR'null' = null ]
+if [ -z "$REMOTE_ADDR" ]
 then
-echo `date`: zfs_raid_control - Blank remote tcpip address >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
-exit 101
+	echo `date`: zfs_raid_control - Blank remote tcpip address >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
+	exit 101
 fi
-if [ $SERVERNAME'null' = null ]
+if [ -z "$SERVERNAME" ]
 then
-echo `date`: software_raid_create - Blank server >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
-exit 101
+	echo `date`: software_raid_create - Blank server >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
+	exit 101
 fi
 
-if [ $SERVERTYPE'null' = null ]
+if [ -z "$SERVERTYPE" ]
 then
-echo `date`: software_raid_create - Blank servertype >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
-exit 101
+	echo `date`: software_raid_create - Blank servertype >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
+	exit 101
 fi
 
 if [ $SERVERTYPE = federatedslave ]
 then
-if [ $SERVERMASTER'null' = null ]
-then
-echo `date`: software_raid_create - Blank servermaster >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
-exit 101
+	if [ -z "$SERVERMASTER" ]
+	then
+		echo `date`: software_raid_create - Blank servermaster >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
+		exit 101
+	fi
 fi
-fi
-
-
 
 if [ `grep -c ^$REMOTE_USER: /opt/karoshi/web_controls/web_access_admin` != 1 ]
 then
-echo `date`: zfs_raid_control - access denied to $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
-exit 101
+	echo `date`: zfs_raid_control - access denied to $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
+	exit 101
 fi
 
 ##########################
 #Language
 ##########################
-LANGCHOICE=englishuk
+
 STYLESHEET=defaultstyle.css
 [ -f /opt/karoshi/web_controls/user_prefs/$REMOTE_USER ] && source /opt/karoshi/web_controls/user_prefs/$REMOTE_USER
-[ -f /opt/karoshi/web_controls/language/$LANGCHOICE/system/software_raid ] || LANGCHOICE=englishuk
-source /opt/karoshi/web_controls/language/$LANGCHOICE/system/software_raid
-[ -f /opt/karoshi/web_controls/language/$LANGCHOICE/all ] || LANGCHOICE=englishuk
-source /opt/karoshi/web_controls/language/$LANGCHOICE/all
+TEXTDOMAIN=karoshi-server
+
 
 ICON1=/images/submenus/system/hdd_add.png
 ICON2=/images/submenus/system/hdd_add_spare.png
@@ -136,8 +132,8 @@ then
 
 if [ `zpool status | grep -c $HOSTNAME-data` = 0 ]
 then
-echo $ERRORMSG18
-exit
+	echo $"A ZFS raid has not been set up on this server."
+	exit
 fi
 
 #Get list of all drives
@@ -160,9 +156,9 @@ CAPACITY=`echo "scale=0; $CAPACITYBYTES/1024/1024/1024" | bc`
 DRIVESCALE=GB
 if [ $CAPACITY -gt 1000 ]
 then
-#Covert capacity to terabytes
-CAPACITY=`echo "scale=2; $CAPACITY/1024" | bc`
-DRIVESCALE=TB
+	#Covert capacity to terabytes
+	CAPACITY=`echo "scale=2; $CAPACITY/1024" | bc`
+	DRIVESCALE=TB
 fi
 
 DISKSIZE=`echo $CAPACITY$DRIVESCALE`
@@ -176,9 +172,9 @@ DRIVE_SN=`echo -e "$HDDATA" | grep SerialNo= | cut -d= -f2`
 DISKICON=hdd.png
 if [ $SMARTSTATUS = 24 ]
 then
-#Drive failing
-DRIVE_STATUS=fail
-DISKICON=hdd_fail.png
+	#Drive failing
+	DRIVE_STATUS=fail
+	DISKICON=hdd_fail.png
 fi
 }
 
@@ -199,10 +195,10 @@ get_drive_info
 
 if [ $SHOW_MENU = yes ]
 then
-echo "<b>$AVAILABLEMSG</b><br><br><table class=\"standard\" style=\"text-align: left;\" border=\"0\" cellpadding=\"2\" cellspacing=\"2\">
-<tbody>"
-SHOW_MENU=no
-SHOW_SUBMIT=yes
+	echo '<b>'$"Available Disks"'</b><br><br><table class="standard" style="text-align: left;" border="0" cellpadding="2" cellspacing="2">
+	<tbody>'
+	SHOW_MENU=no
+	SHOW_SUBMIT=yes
 fi
 
 #Show drive information
@@ -211,17 +207,17 @@ then
 echo "<tr><td style=\"width: 180px;\"><a class=\"info\" href=\"javascript:void(0)\"><img class=\"images\" alt=\"\" src=\"/images/submenus/system/$DISKICON\"><span>$DRIVE - $DISKSIZE</span></a>$DRIVE</td><td style=\"width: 260px;\">$MAKER $DRIVE_SN</td><td>"
 
 #Create list of drives in array to replace
-echo "<select name=\"select\"><option value=\"_ACTION_addspare_DRIVE_$DRIVE"_"DRIVE2_notset"_"\">$ADD_SPAREDISKMSG</option>"
+echo "<select name=\"select\"><option value=\"_ACTION_addspare_DRIVE_$DRIVE"_"DRIVE2_notset"_"\">$"Add this disk as a spare."</option>"
 
 RAIDCOUNTER=0
 while [ $RAIDCOUNTER -lt $RAID_DISKS_COUNT ]
 do
 RAID_DISK=`echo /dev/${RAID_DISKS[$RAIDCOUNTER]}`
-echo "<option value=\"_ACTION_replace_DRIVE_$DRIVE"_"DRIVE2_$RAID_DISK"_"\">$REPLACEDISKMSG - $RAID_DISK</option>"
+echo "<option value=\"_ACTION_replace_DRIVE_$DRIVE"_"DRIVE2_$RAID_DISK"_"\">$"Replace" - $RAID_DISK</option>"
 let RAIDCOUNTER=$RAIDCOUNTER+1
 done
 
-echo "</select></td><td><a class=\"info\" href=\"javascript:void(0)\"><input name=\"submit\" type=\"image\" class=\"images\" src=\"$ICON1\" value=\"\"><span>$ADD_DISKMSG</span></a></td></tr>"
+echo "</select></td><td><a class=\"info\" href=\"javascript:void(0)\"><input name=\"submit\" type=\"image\" class=\"images\" src=\"$ICON1\" value=\"\"><span>$"Add this disk to a raid."</span></a></td></tr>"
 else
 echo "<tr><td style=\"width: 180px;\"><a class=\"info\" href=\"javascript:void(0)\"><img class=\"images\" alt=\"\" src=\"/images/submenus/system/$DISKICON\"><span>$DRIVE - $DISKSIZE</span></a>$DRIVE</td><td style=\"width: 260px;\">$MAKER $DRIVE_SN</td></tr>"
 fi
@@ -229,10 +225,7 @@ fi
 let COUNTER=$COUNTER+1
 done
 
-if [ $SHOW_SUBMIT = yes ]
-then
-echo "</tbody></table><br><br>"
-fi
+[ $SHOW_SUBMIT = yes ] && echo "</tbody></table><br><br>"
 
 #Show raid information
 MOUNTPOINT=`cat /etc/rc2.d/S99zfs-mount | cut -d" " -f3`
@@ -243,49 +236,48 @@ RAID_STATE=`echo -e $ZPOOLINFO | cut -d" " -f7`
 SCANINFORMATION=`echo -e "$ZPOOLSTATUS" | grep scan: | cut -d: -f2`
 RAID_TYPE=`zpool status | grep raidz | tr -cd "A-Za-z0-9- " | sed "s/^ * //g" | cut -d" " -f1`
 
-echo "<b>"$RAIDINFOMSG"</b><br><br>"
-echo "<table class=\"standard\" style=\"text-align: left;\" border=\"0\" cellpadding=\"2\" cellspacing=\"2\"><tbody>
-<tr><td style=\"width: 180px;\">$RAIDNAMEMSG</td><td>$HOSTNAME-data</td></tr>
-<tr><td>$RAIDTYPEMSG</td><td>$RAID_TYPE</td></tr>
-<tr><td>$RAIDSIZEMSG</td><td>$RAID_SIZE</td></tr>
-<tr><td>$RAIDSTATEMSG</td><td>$RAID_STATE</td></tr>
-<tr><td valign=\"top\">$SCANINFOMSG</td><td>$SCANINFORMATION</td></tr>
-"
-
+echo '<b>'$"Raid Information"'</b><br><br>
+<table class="standard" style="text-align: left;" border="0" cellpadding="2" cellspacing="2"><tbody>
+<tr><td style="width: 180px;">'$"Raid Name"'</td><td>'$HOSTNAME'-data</td></tr>
+<tr><td>'$"Raid Type"'</td><td>'$RAID_TYPE'</td></tr>
+<tr><td>'$"Raid Size"'</td><td>'$RAID_SIZE'</td></tr>
+<tr><td>'$"Raid State"'</td><td>'$RAID_STATE'</td></tr>
+<tr><td valign=\"top\">'$"Scan Information"'</td><td>'$SCANINFORMATION'</td></tr>
+'
 
 STATUSSTARTLINE=`echo -e "$ZPOOLSTATUS" | grep -n -w status: | cut -d: -f1`
 if [ ! -z $STATUSSTARTLINE ]
 then
-ACTIONSTARTLINE=`echo -e "$ZPOOLSTATUS" | grep -n -w action: | cut -d: -f1`
-if [ $ACTIONSTARTLINE ]
-then
-let STATUSENDLINE=$ACTIONSTARTLINE-1
-SCANSTARTLINE=`echo -e "$ZPOOLSTATUS" | grep -n -w scan: | cut -d: -f1`
-if [ ! -z $SCANSTARTLINE ]
-then
-let ACTIONENDLINE=$SCANSTARTLINE-1
-#Show extra data on zfs raid
-RAID_STATUS=`echo -e "$ZPOOLSTATUS" | sed -n $STATUSSTARTLINE,$STATUSENDLINE"p" | sed "s/^status: //g"`
-RAID_ACTION=`echo -e "$ZPOOLSTATUS" | sed -n $ACTIONSTARTLINE,$ACTIONENDLINE"p" | sed "s/^action: //g"`
-echo "<tr><td valign=\"top\">$RAIDSTATUSMSG</td><td>$RAID_STATUS</td></tr>"
-echo "<tr><td valign=\"top\">$RAIDACTIONMSG</td><td>$RAID_ACTION</td></tr>"
-fi
-fi
+	ACTIONSTARTLINE=`echo -e "$ZPOOLSTATUS" | grep -n -w action: | cut -d: -f1`
+	if [ $ACTIONSTARTLINE ]
+	then
+		let STATUSENDLINE=$ACTIONSTARTLINE-1
+		SCANSTARTLINE=`echo -e "$ZPOOLSTATUS" | grep -n -w scan: | cut -d: -f1`
+		if [ ! -z $SCANSTARTLINE ]
+		then
+			let ACTIONENDLINE=$SCANSTARTLINE-1
+			#Show extra data on zfs raid
+			RAID_STATUS=`echo -e "$ZPOOLSTATUS" | sed -n $STATUSSTARTLINE,$STATUSENDLINE"p" | sed "s/^status: //g"`
+			RAID_ACTION=`echo -e "$ZPOOLSTATUS" | sed -n $ACTIONSTARTLINE,$ACTIONENDLINE"p" | sed "s/^action: //g"`
+			echo '<tr><td valign=\"top\">'$"Raid Status"'</td><td>'$RAID_STATUS'</td></tr>'
+			echo '<tr><td valign=\"top\">'$"Raid Action"'</td><td>'$RAID_ACTION'</td></tr>'
+		fi
+	fi
 fi
 
 COUNTER=0
 while [ $COUNTER -lt $RAID_DISKS_COUNT ]
 do
-RAID_DISK=`echo /dev/${RAID_DISKS[$COUNTER]}`
-#Get disk status
-DISKSTATUS=$ACTIVEMSG
-[ `echo -e "$ZPOOLSTATUS" | grep ${RAID_DISKS[$COUNTER]} | grep -c OFFLINE` -gt 0 ] && DISKSTATUS=$OFFLINEMSG
-[ `echo -e "$ZPOOLSTATUS" | grep ${RAID_DISKS[$COUNTER]} | grep -c AVAIL` -gt 0 ] && DISKSTATUS=$SPAREMSG
-ICON=$ICON3
-DRIVE=$RAID_DISK
-get_drive_info
-echo "<tr><td><a class=\"info\" href=\"javascript:void(0)\"><img class=\"images\" alt=\"\" src=\"/images/submenus/system/$DISKICON\"><span>$DRIVE - $DISKSIZE</span></a>"$RAID_DISK - $DISKSTATUS"</td><td>$MAKER $DRIVE_SN</td></tr>"
-let COUNTER=$COUNTER+1
+	RAID_DISK=`echo /dev/${RAID_DISKS[$COUNTER]}`
+	#Get disk status
+	DISKSTATUS=$"active"
+	[ `echo -e "$ZPOOLSTATUS" | grep ${RAID_DISKS[$COUNTER]} | grep -c OFFLINE` -gt 0 ] && DISKSTATUS=$"offline"
+	[ `echo -e "$ZPOOLSTATUS" | grep ${RAID_DISKS[$COUNTER]} | grep -c AVAIL` -gt 0 ] && DISKSTATUS=$"spare"
+	ICON=$ICON3
+	DRIVE=$RAID_DISK
+	get_drive_info
+	echo "<tr><td><a class=\"info\" href=\"javascript:void(0)\"><img class=\"images\" alt=\"\" src=\"/images/submenus/system/$DISKICON\"><span>$DRIVE - $DISKSIZE</span></a>"$RAID_DISK - $DISKSTATUS"</td><td>$MAKER $DRIVE_SN</td></tr>"
+	let COUNTER=$COUNTER+1
 done
 echo "</tbody></table><br>"
 fi
@@ -298,8 +290,8 @@ ssh -x -o PasswordAuthentication=no $SERVERNAME '
 
 if [ `zpool status | grep -c $HOSTNAME-data` = 0 ]
 then
-echo '$ERRORMSG18'
-exit
+	echo '$"A ZFS raid has not been set up on this server."'
+	exit
 fi
 
 #Get list of all drives
@@ -361,7 +353,7 @@ get_drive_info
 
 if [ $SHOW_MENU = yes ]
 then
-echo "<b>'$AVAILABLEMSG'</b><br><br><table class=\"standard\" style=\"text-align: left;\" border=\"0\" cellpadding=\"2\" cellspacing=\"2\">
+echo "<b>'$"Available Disks"'</b><br><br><table class=\"standard\" style=\"text-align: left;\" border=\"0\" cellpadding=\"2\" cellspacing=\"2\">
 <tbody>"
 SHOW_MENU=no
 SHOW_SUBMIT=yes
@@ -373,17 +365,17 @@ then
 echo "<tr><td style=\"width: 180px;\"><a class=\"info\" href=\"javascript:void(0)\"><img class=\"images\" alt=\"\" src=\"/images/submenus/system/$DISKICON\"><span>$DRIVE - $DISKSIZE</span></a>$DRIVE</td><td style=\"width: 260px;\">$MAKER $DRIVE_SN</td><td>"
 
 #Create list of drives in array to replace
-echo "<select name=\"select\"><option value=\"_ACTION_addspare_DRIVE_$DRIVE"_"DRIVE2_notset"_"\">'$ADD_SPAREDISKMSG'</option>"
+echo "<select name=\"select\"><option value=\"_ACTION_addspare_DRIVE_$DRIVE"_"DRIVE2_notset"_"\">'$"Add this disk as a spare."'</option>"
 
 RAIDCOUNTER=0
 while [ $RAIDCOUNTER -lt $RAID_DISKS_COUNT ]
 do
 RAID_DISK=`echo /dev/${RAID_DISKS[$RAIDCOUNTER]}`
-echo "<option value=\"_ACTION_replace_DRIVE_$DRIVE"_"DRIVE2_$RAID_DISK"_"\">'$REPLACEDISKMSG' - $RAID_DISK</option>"
+echo "<option value=\"_ACTION_replace_DRIVE_$DRIVE"_"DRIVE2_$RAID_DISK"_"\">'$"Replace"' - $RAID_DISK</option>"
 let RAIDCOUNTER=$RAIDCOUNTER+1
 done
 
-echo "</select></td><td><a class=\"info\" href=\"javascript:void(0)\"><input name=\"submit\" type=\"image\" class=\"images\" src=\"'$ICON1'\" value=\"\"><span>'$ADD_DISKMSG'</span></a></td></tr>"
+echo "</select></td><td><a class=\"info\" href=\"javascript:void(0)\"><input name=\"submit\" type=\"image\" class=\"images\" src=\"'$ICON1'\" value=\"\"><span>'$"Add this disk to a raid."'</span></a></td></tr>"
 else
 echo "<tr><td style=\"width: 180px;\"><a class=\"info\" href=\"javascript:void(0)\"><img class=\"images\" alt=\"\" src=\"/images/submenus/system/$DISKICON\"><span>$DRIVE - $DISKSIZE</span></a>$DRIVE</td><td style=\"width: 260px;\">$MAKER $DRIVE_SN</td></tr>"
 fi
@@ -405,13 +397,13 @@ RAID_STATE=`echo -e $ZPOOLINFO | cut -d" " -f7`
 SCANINFORMATION=`echo -e "$ZPOOLSTATUS" | grep scan: | cut -d: -f2`
 RAID_TYPE=`zpool status | grep raidz | tr -cd "A-Za-z0-9- " | sed "s/^ * //g" | cut -d" " -f1`
 
-echo "<b>"'$RAIDINFOMSG'"</b><br><br>"
+echo "<b>"'$"Raid Information"'"</b><br><br>"
 echo "<table class=\"standard\" style=\"text-align: left;\" border=\"0\" cellpadding=\"2\" cellspacing=\"2\"><tbody>
-<tr><td style=\"width: 180px;\">'$RAIDNAMEMSG'</td><td>$HOSTNAME-data</td></tr>
-<tr><td>'$RAIDTYPEMSG'</td><td>$RAID_TYPE</td></tr>
-<tr><td>'$RAIDSIZEMSG'</td><td>$RAID_SIZE</td></tr>
-<tr><td>'$RAIDSTATEMSG'</td><td>$RAID_STATE</td></tr>
-<tr><td valign=\"top\">'$SCANINFOMSG'</td><td>$SCANINFORMATION</td></tr>
+<tr><td style=\"width: 180px;\">'$"Raid Name"'</td><td>$HOSTNAME-data</td></tr>
+<tr><td>'$"Raid Type"'</td><td>$RAID_TYPE</td></tr>
+<tr><td>'$"Raid Size"'</td><td>$RAID_SIZE</td></tr>
+<tr><td>'$"Raid State"'</td><td>$RAID_STATE</td></tr>
+<tr><td valign=\"top\">'$"Scan Information"'</td><td>$SCANINFORMATION</td></tr>
 "
 
 
@@ -429,8 +421,8 @@ let ACTIONENDLINE=$SCANSTARTLINE-1
 #Show extra data on zfs raid
 RAID_STATUS=`echo -e "$ZPOOLSTATUS" | sed -n $STATUSSTARTLINE,$STATUSENDLINE"p" | sed "s/^status: //g"`
 RAID_ACTION=`echo -e "$ZPOOLSTATUS" | sed -n $ACTIONSTARTLINE,$ACTIONENDLINE"p" | sed "s/^action: //g"`
-echo "<tr><td valign=\"top\">'$RAIDSTATUSMSG'</td><td>$RAID_STATUS</td></tr>"
-echo "<tr><td valign=\"top\">'$RAIDACTIONMSG'</td><td>$RAID_ACTION</td></tr>"
+echo "<tr><td valign=\"top\">'$"Raid Status"'</td><td>$RAID_STATUS</td></tr>"
+echo "<tr><td valign=\"top\">'$"Raid Action"'</td><td>$RAID_ACTION</td></tr>"
 fi
 fi
 fi
@@ -440,9 +432,9 @@ while [ $COUNTER -lt $RAID_DISKS_COUNT ]
 do
 RAID_DISK=`echo /dev/${RAID_DISKS[$COUNTER]}`
 #Get disk status
-DISKSTATUS='$ACTIVEMSG'
-[ `echo -e "$ZPOOLSTATUS" | grep ${RAID_DISKS[$COUNTER]} | grep -c OFFLINE` -gt 0 ] && DISKSTATUS='$OFFLINEMSG'
-[ `echo -e "$ZPOOLSTATUS" | grep ${RAID_DISKS[$COUNTER]} | grep -c AVAIL` -gt 0 ] && DISKSTATUS='$SPAREMSG'
+DISKSTATUS='$"active"'
+[ `echo -e "$ZPOOLSTATUS" | grep ${RAID_DISKS[$COUNTER]} | grep -c OFFLINE` -gt 0 ] && DISKSTATUS='$"offline"'
+[ `echo -e "$ZPOOLSTATUS" | grep ${RAID_DISKS[$COUNTER]} | grep -c AVAIL` -gt 0 ] && DISKSTATUS='$"spare"'
 ICON=$ICON3
 DRIVE=$RAID_DISK
 get_drive_info
