zfs_raid - no longer limited to one zfs raid per server. software_raid - fix to stop showing available drives that are actually in use in a zfs array. buildserver - now installs hdparm

diff --git a/serversetup/web_controls/scripts/exec/pdc/zfs_raid_control b/serversetup/web_controls/scripts/exec/pdc/zfs_raid_control
--- a/serversetup/web_controls/scripts/exec/pdc/zfs_raid_control
+++ b/serversetup/web_controls/scripts/exec/pdc/zfs_raid_control
@@ -29,8 +29,8 @@ LOG_DATE=`date +%F`
 ########################
 if ! test -f /opt/karoshi/web_controls/checksums/admin_checksums/zfs_raid_control_cgi
 then
-echo `date`: zfs_raid_control - No admin MD5Checksum >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
-exit 101
+	echo `date`: zfs_raid_control - No admin MD5Checksum >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
+	exit 101
 fi
 source /opt/karoshi/web_controls/checksums/admin_checksums/zfs_raid_control_cgi
 MD5SUM=`md5sum /var/www/cgi-bin_karoshi/admin/zfs_raid_control.cgi | cut -d' ' -f1`
@@ -124,31 +124,30 @@ ICON3=/images/submenus/system/hdd_remove.png
 ICON4=/images/submenus/system/hdd_fail.png
 
 
-
 if [ $SERVERNAME = `hostname-fqdn` ]
 then
 
 #Check that a zfs raid has been set up on this server
 
-if [ `zpool status | grep -c $HOSTNAME-data` = 0 ]
+if [ `zpool status | grep -c pool:` = 0 ]
 then
 	echo $"A ZFS raid has not been set up on this server."
+	sleep 3
+	echo "</form><form METHOD=POST ACTION=\"/cgi-bin/admin/zfs_raid_create.cgi\" target=\"_top\" name = \"frm\">
+<input type=\"hidden\" name=\"_SERVERNAME_\" value=\"$SERVERNAME\">
+<input type=\"hidden\" name=\"_SERVERTYPE_\" value=\"$SERVERTYPE\">
+<input type=\"hidden\" name=\"_SERVERMASTER_\" value=\"$SERVERMASTER\">
+</form><script>document.frm.submit();</script>"
 	exit
 fi
 
 #Get list of all drives
-ALL_DRIVES=( `parted -l -s | grep Disk | sed "s/Error: //g" | sed "s/Disk //g" | grep /dev/sd | cut -d: -f1 | tr -cd "A-Za-z0-9/\n "` )
+ALL_DRIVES=( /dev/sd? )
 ALL_DRIVES_COUNT=${#ALL_DRIVES[@]}
 
-#Get a list of active drives in the array
-RAID_DISKS=( `zpool status $HOSTNAME-data | grep "ONLINE\|SPARE\|OFFLINE" | sed "s/\\t//g" | sed "s/^ * //g" | cut -d" " -f1 | grep -v "replacing\|state:\|$HOSTNAME-data\|raidz"` )
-RAID_DISKS_COUNT=`echo ${#RAID_DISKS[@]}`
 
-
+#Get drive information
 function get_drive_info {
-#Get drive information
-#Get drive information
-
 SMARTINFO=`smartctl -i $DRIVE | tr -cd "A-Za-z0-9:=,/\n "`
 CAPACITYBYTES=`echo -e "$SMARTINFO" | grep ^User | sed "s/ * / /g" | cut -d" " -f3 | tr -cd "0-9"`
 #Convert capacity to gigabytes
@@ -178,135 +177,136 @@ then
 fi
 }
 
+##########################
+#Show a list of spare drives
+##########################
 #Get list of all unmounted drives and display properties
+function show_spare_drives {
 COUNTER=0
 SHOW_MENU=yes
 SHOW_SUBMIT=no
 echo "<input type=\"hidden\" name=\"_SERVERNAME_\" value=\"$SERVERNAME\">"
 echo "<input type=\"hidden\" name=\"_SERVERTYPE_\" value=\"$SERVERTYPE\">"
 echo "<input type=\"hidden\" name=\"_SERVERMASTER_\" value=\"$SERVERMASTER\">"
+
+echo '<table class="standard" style="text-align: left;" border="0" cellpadding="2" cellspacing="2"><tbody>'
+
 while [ $COUNTER -lt $ALL_DRIVES_COUNT ]
 do
 DRIVE=${ALL_DRIVES[$COUNTER]}
 DRIVE_SHORT=`echo $DRIVE | sed "s/\/dev\///g"` 
-if [ `mount | grep -c $DRIVE` = 0 ] && [ `zpool status | grep -c $DRIVE_SHORT` = 0 ]
+
+
+if [ `mount | grep -c $DRIVE` = 0 ] && [ `zpool status | grep -c $DRIVE_SHORT` = 0 ] && [ `cat /proc/mdstat | grep -c $DRIVE_SHORT` = 0 ]
 then
 get_drive_info
 
-if [ $SHOW_MENU = yes ]
-then
-	echo '<b>'$"Available Disks"'</b><br><br><table class="standard" style="text-align: left;" border="0" cellpadding="2" cellspacing="2">
-	<tbody>'
-	SHOW_MENU=no
-	SHOW_SUBMIT=yes
-fi
 
 #Show drive information
 if [ $DRIVE_STATUS = ok ]
 then
 echo "<tr><td style=\"width: 180px;\"><a class=\"info\" href=\"javascript:void(0)\"><img class=\"images\" alt=\"\" src=\"/images/submenus/system/$DISKICON\"><span>$DRIVE - $DISKSIZE</span></a>$DRIVE</td><td style=\"width: 260px;\">$MAKER $DRIVE_SN</td><td>"
-
 #Create list of drives in array to replace
-echo "<select name=\"select\"><option value=\"_ACTION_addspare_DRIVE_$DRIVE"_"DRIVE2_notset"_"\">$"Add this disk as a spare."</option>"
+echo '<select name="select"><option value="_POOL_'$POOLNAME'_ACTION_addspare_DRIVE_'$DRIVE'_DRIVE2_notset_">'$"Add spare"'</option>'
 
-RAIDCOUNTER=0
-while [ $RAIDCOUNTER -lt $RAID_DISKS_COUNT ]
+for RAIDDISK in $ZPOOLDRIVES
 do
-RAID_DISK=`echo /dev/${RAID_DISKS[$RAIDCOUNTER]}`
-echo "<option value=\"_ACTION_replace_DRIVE_$DRIVE"_"DRIVE2_$RAID_DISK"_"\">$"Replace" - $RAID_DISK</option>"
-let RAIDCOUNTER=$RAIDCOUNTER+1
+	RAIDDISK=`echo /dev/$RAIDDISK`
+	echo '<option value="_POOL_'$POOLNAME'_ACTION_replace_DRIVE_'$DRIVE'_DRIVE2_'$RAIDDISK'_">'$"Replace"' - '$RAIDDISK'</option>'
 done
 
-echo "</select></td><td><a class=\"info\" href=\"javascript:void(0)\"><input name=\"submit\" type=\"image\" class=\"images\" src=\"$ICON1\" value=\"\"><span>$"Add this disk to a raid."</span></a></td></tr>"
+echo '</select></td><td><a class="info" href="javascript:void(0)"><input name="submit" type="image" class="images" src="'$ICON1'" value=""><span>'$"Add this disk to a raid."'</span></a></td></tr>'
 else
 echo "<tr><td style=\"width: 180px;\"><a class=\"info\" href=\"javascript:void(0)\"><img class=\"images\" alt=\"\" src=\"/images/submenus/system/$DISKICON\"><span>$DRIVE - $DISKSIZE</span></a>$DRIVE</td><td style=\"width: 260px;\">$MAKER $DRIVE_SN</td></tr>"
 fi
 fi
 let COUNTER=$COUNTER+1
 done
+echo "</tbody></table><br><br>"
+}
 
-[ $SHOW_SUBMIT = yes ] && echo "</tbody></table><br><br>"
+##########################
+#Get a list of all available pools
+##########################
+for POOLNAME in `zpool status | grep pool: | cut -d: -f2 | sed "s/ //g"`
+do
+
+#Get a list of active drives in the array
+ZPOOLDRIVES=`zpool status $POOLNAME | grep "ONLINE\|SPARE\|OFFLINE\|AVAIL" | sed "s/\\t//g" | sed "s/^ * //g" | cut -d" " -f1 | grep -v "replacing\|state:\|$POOLNAME\|raidz"`
 
 #Show raid information
-MOUNTPOINT=`cat /etc/rc2.d/S99zfs-mount | cut -d" " -f3`
-ZPOOLINFO=`zpool list $HOSTNAME-data | sed -n 2,2p | sed "s/ * / /g"`
-ZPOOLSTATUS=`zpool status $HOSTNAME-data`
+MOUNTPOINT=`cat /etc/rc2.d/S99zfs-mount-$POOLNAME | cut -d" " -f3`
+ZPOOLINFO=`zpool list $POOLNAME | sed -n 2,2p | sed "s/ * / /g"`
+ZPOOLSTATUS=`zpool status $POOLNAME`
 RAID_SIZE=`df -h | grep $MOUNTPOINT | sed "s/ * / /g" | cut -d" " -f2` 
 RAID_STATE=`echo -e $ZPOOLINFO | cut -d" " -f7`
 SCANINFORMATION=`echo -e "$ZPOOLSTATUS" | grep scan: | cut -d: -f2`
-RAID_TYPE=`zpool status | grep raidz | tr -cd "A-Za-z0-9- " | sed "s/^ * //g" | cut -d" " -f1`
+RAID_TYPE=`zpool status $POOLNAME | grep raidz | tr -cd "A-Za-z0-9- " | sed "s/^ * //g" | cut -d" " -f1`
 
 echo '<b>'$"Raid Information"'</b><br><br>
 <table class="standard" style="text-align: left;" border="0" cellpadding="2" cellspacing="2"><tbody>
-<tr><td style="width: 180px;">'$"Raid Name"'</td><td>'$HOSTNAME'-data</td></tr>
+<tr><td style="width: 180px;">'$"Raid Name"'</td><td>'$POOLNAME'</td></tr>
 <tr><td>'$"Raid Type"'</td><td>'$RAID_TYPE'</td></tr>
 <tr><td>'$"Raid Size"'</td><td>'$RAID_SIZE'</td></tr>
 <tr><td>'$"Raid State"'</td><td>'$RAID_STATE'</td></tr>
-<tr><td valign=\"top\">'$"Scan Information"'</td><td>'$SCANINFORMATION'</td></tr>
-'
+<tr><td>'$"Mount Point"'</td><td>'$MOUNTPOINT'</td></tr>
+<tr><td valign="top">'$"Scan Information"'</td><td>'$SCANINFORMATION'</td></tr>'
 
-STATUSSTARTLINE=`echo -e "$ZPOOLSTATUS" | grep -n -w status: | cut -d: -f1`
-if [ ! -z $STATUSSTARTLINE ]
-then
-	ACTIONSTARTLINE=`echo -e "$ZPOOLSTATUS" | grep -n -w action: | cut -d: -f1`
-	if [ $ACTIONSTARTLINE ]
-	then
-		let STATUSENDLINE=$ACTIONSTARTLINE-1
-		SCANSTARTLINE=`echo -e "$ZPOOLSTATUS" | grep -n -w scan: | cut -d: -f1`
-		if [ ! -z $SCANSTARTLINE ]
-		then
-			let ACTIONENDLINE=$SCANSTARTLINE-1
-			#Show extra data on zfs raid
-			RAID_STATUS=`echo -e "$ZPOOLSTATUS" | sed -n $STATUSSTARTLINE,$STATUSENDLINE"p" | sed "s/^status: //g"`
-			RAID_ACTION=`echo -e "$ZPOOLSTATUS" | sed -n $ACTIONSTARTLINE,$ACTIONENDLINE"p" | sed "s/^action: //g"`
-			echo '<tr><td valign=\"top\">'$"Raid Status"'</td><td>'$RAID_STATUS'</td></tr>'
-			echo '<tr><td valign=\"top\">'$"Raid Action"'</td><td>'$RAID_ACTION'</td></tr>'
-		fi
-	fi
-fi
 
-COUNTER=0
-while [ $COUNTER -lt $RAID_DISKS_COUNT ]
-do
-	RAID_DISK=`echo /dev/${RAID_DISKS[$COUNTER]}`
+for ZPOOLDRIVE in $ZPOOLDRIVES
+	do
+	DRIVE=/dev/$ZPOOLDRIVE
 	#Get disk status
 	DISKSTATUS=$"Active"
-	[ `echo -e "$ZPOOLSTATUS" | grep ${RAID_DISKS[$COUNTER]} | grep -c OFFLINE` -gt 0 ] && DISKSTATUS=$"offline"
-	[ `echo -e "$ZPOOLSTATUS" | grep ${RAID_DISKS[$COUNTER]} | grep -c AVAIL` -gt 0 ] && DISKSTATUS=$"spare"
-	ICON=$ICON3
-	DRIVE=$RAID_DISK
+	SHOWREMOVE=no
+	[ `echo -e "$ZPOOLSTATUS" | grep $ZPOOLDRIVE | grep -c OFFLINE` -gt 0 ] && DISKSTATUS=$"Offline"
+	if [ `echo -e "$ZPOOLSTATUS" | grep $ZPOOLDRIVE | grep -c AVAIL` -gt 0 ]
+	then
+		DISKSTATUS=$"Spare"
+		SHOWREMOVE=yes
+	fi
+
 	get_drive_info
-	echo "<tr><td><a class=\"info\" href=\"javascript:void(0)\"><img class=\"images\" alt=\"\" src=\"/images/submenus/system/$DISKICON\"><span>$DRIVE - $DISKSIZE</span></a>"$RAID_DISK - $DISKSTATUS"</td><td>$MAKER $DRIVE_SN</td></tr>"
-	let COUNTER=$COUNTER+1
+	
+	echo "<tr><td><a class=\"info\" href=\"javascript:void(0)\"><img class=\"images\" alt=\"\" src=\"/images/submenus/system/$DISKICON\"><span>$DRIVE - $DISKSIZE</span></a> "$DRIVE - $DISKSTATUS"</td><td>$MAKER $DRIVE_SN</td>"
+[ $SHOWREMOVE = yes ] && echo "<td>
+<a class=\"info\" href=\"javascript:void(0)\"><input name=\"_SERVERTYPE_$SERVERTYPE"_"SERVERNAME_$SERVERNAME"_"ACTION_removespare_POOL_$POOLNAME"_"DRIVE_$DRIVE"_"DRIVE2_notset"_"\" type=\"image\" class=\"images\" src="$ICON3" value=\"\"><span>"$"Remove spare""</span></a>
+</td>"
+
+echo "</tr>"
+	done
+echo '</tbody></table><br>'
+#Show any spare drives
+show_spare_drives
+echo "</form><form METHOD=POST ACTION=\"/cgi-bin/admin/zfs_raid_control2.cgi\" target=\"_top\" name = \"frm\">"
 done
-echo "</tbody></table><br>"
 fi
 
 if [ $SERVERTYPE = network ] || [ $SERVERTYPE = federated ] && [ $SERVERNAME != `hostname-fqdn` ]
 then
 ssh -x -o PasswordAuthentication=no $SERVERNAME '
-
 #Check that a zfs raid has been set up on this server
 
-if [ `zpool status | grep -c $HOSTNAME-data` = 0 ]
+if [ `zpool status | grep -c pool:` = 0 ]
 then
 	echo '$"A ZFS raid has not been set up on this server."'
+	sleep 3
+	echo "</form><form METHOD=POST ACTION=\"/cgi-bin/admin/zfs_raid_create.cgi\" target=\"_top\" name = \"frm\">
+<input type=\"hidden\" name=\"_SERVERNAME_\" value=\"'$SERVERNAME'\">
+<input type=\"hidden\" name=\"_SERVERTYPE_\" value=\"'$SERVERTYPE'\">
+<input type=\"hidden\" name=\"_SERVERMASTER_\" value=\"'$SERVERMASTER'\">
+<input type=\"hidden\" name=\"_CREATETYPE_\" value=\"reuse\">
+</form><script>document.frm.submit();</script>"
 	exit
 fi
 
 #Get list of all drives
-ALL_DRIVES=( `parted -l -s | grep Disk | sed "s/Error: //g" | sed "s/Disk //g" | grep /dev/sd | cut -d: -f1 | tr -cd "A-Za-z0-9/\n "` )
+ALL_DRIVES=( /dev/sd? )
 ALL_DRIVES_COUNT=${#ALL_DRIVES[@]}
 
-#Get a list of active drives in the array
-RAID_DISKS=( `zpool status $HOSTNAME-data | grep "ONLINE\|SPARE\|OFFLINE" | sed "s/\\t//g" | sed "s/^ * //g" | cut -d" " -f1 | grep -v "replacing\|state:\|$HOSTNAME-data\|raidz"` )
-RAID_DISKS_COUNT=`echo ${#RAID_DISKS[@]}`
 
-
+#Get drive information
 function get_drive_info {
-#Get drive information
-#Get drive information
-
 SMARTINFO=`smartctl -i $DRIVE | tr -cd "A-Za-z0-9:=,/\n "`
 CAPACITYBYTES=`echo -e "$SMARTINFO" | grep ^User | sed "s/ * / /g" | cut -d" " -f3 | tr -cd "0-9"`
 #Convert capacity to gigabytes
@@ -314,9 +314,9 @@ CAPACITY=`echo "scale=0; $CAPACITYBYTES/1024/1024/1024" | bc`
 DRIVESCALE=GB
 if [ $CAPACITY -gt 1000 ]
 then
-#Covert capacity to terabytes
-CAPACITY=`echo "scale=2; $CAPACITY/1024" | bc`
-DRIVESCALE=TB
+	#Covert capacity to terabytes
+	CAPACITY=`echo "scale=2; $CAPACITY/1024" | bc`
+	DRIVESCALE=TB
 fi
 
 DISKSIZE=`echo $CAPACITY$DRIVESCALE`
@@ -330,49 +330,48 @@ DRIVE_SN=`echo -e "$HDDATA" | grep SerialNo= | cut -d= -f2`
 DISKICON=hdd.png
 if [ $SMARTSTATUS = 24 ]
 then
-#Drive failing
-DRIVE_STATUS=fail
-DISKICON=hdd_fail.png
+	#Drive failing
+	DRIVE_STATUS=fail
+	DISKICON=hdd_fail.png
 fi
 }
 
+##########################
+#Show a list of spare drives
+##########################
 #Get list of all unmounted drives and display properties
+function show_spare_drives {
 COUNTER=0
 SHOW_MENU=yes
 SHOW_SUBMIT=no
 echo "<input type=\"hidden\" name=\"_SERVERNAME_\" value=\"'$SERVERNAME'\">"
 echo "<input type=\"hidden\" name=\"_SERVERTYPE_\" value=\"'$SERVERTYPE'\">"
 echo "<input type=\"hidden\" name=\"_SERVERMASTER_\" value=\"'$SERVERMASTER'\">"
+
+echo "<table class=\"standard\" style=\"text-align: left;\" border=\"0\" cellpadding=\"2\" cellspacing=\"2\"><tbody>"
+
 while [ $COUNTER -lt $ALL_DRIVES_COUNT ]
 do
 DRIVE=${ALL_DRIVES[$COUNTER]}
 DRIVE_SHORT=`echo $DRIVE | sed "s/\/dev\///g"` 
-if [ `mount | grep -c $DRIVE` = 0 ] && [ `zpool status | grep -c $DRIVE_SHORT` = 0 ]
+
+
+if [ `mount | grep -c $DRIVE` = 0 ] && [ `zpool status | grep -c $DRIVE_SHORT` = 0 ] && [ `cat /proc/mdstat | grep -c $DRIVE_SHORT` = 0 ]
 then
 get_drive_info
 
-if [ $SHOW_MENU = yes ]
-then
-echo "<b>'$"Available Disks"'</b><br><br><table class=\"standard\" style=\"text-align: left;\" border=\"0\" cellpadding=\"2\" cellspacing=\"2\">
-<tbody>"
-SHOW_MENU=no
-SHOW_SUBMIT=yes
-fi
 
 #Show drive information
 if [ $DRIVE_STATUS = ok ]
 then
 echo "<tr><td style=\"width: 180px;\"><a class=\"info\" href=\"javascript:void(0)\"><img class=\"images\" alt=\"\" src=\"/images/submenus/system/$DISKICON\"><span>$DRIVE - $DISKSIZE</span></a>$DRIVE</td><td style=\"width: 260px;\">$MAKER $DRIVE_SN</td><td>"
-
 #Create list of drives in array to replace
-echo "<select name=\"select\"><option value=\"_ACTION_addspare_DRIVE_$DRIVE"_"DRIVE2_notset"_"\">'$"Add this disk as a spare."'</option>"
+echo "<select name=\"select\"><option value=\"_POOL_$POOLNAME"_"ACTION_addspare_DRIVE_$DRIVE"_"DRIVE2_notset_\">'$"Add spare"'</option>"
 
-RAIDCOUNTER=0
-while [ $RAIDCOUNTER -lt $RAID_DISKS_COUNT ]
+for RAIDDISK in $ZPOOLDRIVES
 do
-RAID_DISK=`echo /dev/${RAID_DISKS[$RAIDCOUNTER]}`
-echo "<option value=\"_ACTION_replace_DRIVE_$DRIVE"_"DRIVE2_$RAID_DISK"_"\">'$"Replace"' - $RAID_DISK</option>"
-let RAIDCOUNTER=$RAIDCOUNTER+1
+	RAIDDISK=`echo /dev/$RAIDDISK`
+	echo "<option value="_POOL_$POOLNAME\_ACTION_replace_DRIVE_$DRIVE\_DRIVE2_$RAIDDISK\_">'$"Replace"' - $RAIDDISK</option>"
 done
 
 echo "</select></td><td><a class=\"info\" href=\"javascript:void(0)\"><input name=\"submit\" type=\"image\" class=\"images\" src=\"'$ICON1'\" value=\"\"><span>'$"Add this disk to a raid."'</span></a></td></tr>"
@@ -382,66 +381,66 @@ fi
 fi
 let COUNTER=$COUNTER+1
 done
-
-if [ $SHOW_SUBMIT = yes ]
-then
 echo "</tbody></table><br><br>"
-fi
+}
+
+##########################
+#Get a list of all available pools
+##########################
+for POOLNAME in `zpool status | grep pool: | cut -d: -f2 | sed "s/ //g"`
+do
+
+#Get a list of active drives in the array
+ZPOOLDRIVES=`zpool status $POOLNAME | grep "ONLINE\|SPARE\|OFFLINE\|AVAIL" | sed "s/\\t//g" | sed "s/^ * //g" | cut -d" " -f1 | grep -v "replacing\|state:\|$POOLNAME\|raidz"`
 
 #Show raid information
-MOUNTPOINT=`cat /etc/rc2.d/S99zfs-mount | cut -d" " -f3`
-ZPOOLINFO=`zpool list $HOSTNAME-data | sed -n 2,2p | sed "s/ * / /g"`
-ZPOOLSTATUS=`zpool status $HOSTNAME-data`
+MOUNTPOINT=`cat /etc/rc2.d/S99zfs-mount-$POOLNAME | cut -d" " -f3`
+ZPOOLINFO=`zpool list $POOLNAME | sed -n 2,2p | sed "s/ * / /g"`
+ZPOOLSTATUS=`zpool status $POOLNAME`
 RAID_SIZE=`df -h | grep $MOUNTPOINT | sed "s/ * / /g" | cut -d" " -f2` 
 RAID_STATE=`echo -e $ZPOOLINFO | cut -d" " -f7`
 SCANINFORMATION=`echo -e "$ZPOOLSTATUS" | grep scan: | cut -d: -f2`
-RAID_TYPE=`zpool status | grep raidz | tr -cd "A-Za-z0-9- " | sed "s/^ * //g" | cut -d" " -f1`
+RAID_TYPE=`zpool status $POOLNAME | grep raidz | tr -cd "A-Za-z0-9- " | sed "s/^ * //g" | cut -d" " -f1`
 
-echo "<b>"'$"Raid Information"'"</b><br><br>"
-echo "<table class=\"standard\" style=\"text-align: left;\" border=\"0\" cellpadding=\"2\" cellspacing=\"2\"><tbody>
-<tr><td style=\"width: 180px;\">'$"Raid Name"'</td><td>$HOSTNAME-data</td></tr>
+echo "<b>'$"Raid Information"'</b><br><br>
+<table class=\"standard\" style=\"text-align: left;\" border=\"0\" cellpadding=\"2\" cellspacing=\"2\"><tbody>
+<tr><td style=\"width: 180px;\">'$"Raid Name"'</td><td>$POOLNAME</td></tr>
 <tr><td>'$"Raid Type"'</td><td>$RAID_TYPE</td></tr>
 <tr><td>'$"Raid Size"'</td><td>$RAID_SIZE</td></tr>
 <tr><td>'$"Raid State"'</td><td>$RAID_STATE</td></tr>
-<tr><td valign=\"top\">'$"Scan Information"'</td><td>$SCANINFORMATION</td></tr>
-"
+<tr><td>'$"Mount Point"'</td><td>$MOUNTPOINT</td></tr>
+<tr><td valign="top">'$"Scan Information"'</td><td>$SCANINFORMATION</td></tr>"
 
 
-STATUSSTARTLINE=`echo -e "$ZPOOLSTATUS" | grep -n -w status: | cut -d: -f1`
-if [ ! -z $STATUSSTARTLINE ]
-then
-ACTIONSTARTLINE=`echo -e "$ZPOOLSTATUS" | grep -n -w action: | cut -d: -f1`
-if [ $ACTIONSTARTLINE ]
-then
-let STATUSENDLINE=$ACTIONSTARTLINE-1
-SCANSTARTLINE=`echo -e "$ZPOOLSTATUS" | grep -n -w scan: | cut -d: -f1`
-if [ ! -z $SCANSTARTLINE ]
-then
-let ACTIONENDLINE=$SCANSTARTLINE-1
-#Show extra data on zfs raid
-RAID_STATUS=`echo -e "$ZPOOLSTATUS" | sed -n $STATUSSTARTLINE,$STATUSENDLINE"p" | sed "s/^status: //g"`
-RAID_ACTION=`echo -e "$ZPOOLSTATUS" | sed -n $ACTIONSTARTLINE,$ACTIONENDLINE"p" | sed "s/^action: //g"`
-echo "<tr><td valign=\"top\">'$"Raid Status"'</td><td>$RAID_STATUS</td></tr>"
-echo "<tr><td valign=\"top\">'$"Raid Action"'</td><td>$RAID_ACTION</td></tr>"
-fi
-fi
-fi
+for ZPOOLDRIVE in $ZPOOLDRIVES
+	do
+	DRIVE=/dev/$ZPOOLDRIVE
+	SHOWREMOVE=no
+	#Get disk status
+	DISKSTATUS=$"Active"
+	[ `echo -e "$ZPOOLSTATUS" | grep $DRIVE | grep -c OFFLINE` -gt 0 ] && DISKSTATUS=$"Offline"
 
-COUNTER=0
-while [ $COUNTER -lt $RAID_DISKS_COUNT ]
-do
-RAID_DISK=`echo /dev/${RAID_DISKS[$COUNTER]}`
-#Get disk status
-DISKSTATUS='$"Active"'
-[ `echo -e "$ZPOOLSTATUS" | grep ${RAID_DISKS[$COUNTER]} | grep -c OFFLINE` -gt 0 ] && DISKSTATUS='$"offline"'
-[ `echo -e "$ZPOOLSTATUS" | grep ${RAID_DISKS[$COUNTER]} | grep -c AVAIL` -gt 0 ] && DISKSTATUS='$"spare"'
-ICON=$ICON3
-DRIVE=$RAID_DISK
-get_drive_info
-echo "<tr><td><a class=\"info\" href=\"javascript:void(0)\"><img class=\"images\" alt=\"\" src=\"/images/submenus/system/$DISKICON\"><span>$DRIVE - $DISKSIZE</span></a>"$RAID_DISK - $DISKSTATUS"</td><td>$MAKER $DRIVE_SN</td></tr>"
-let COUNTER=$COUNTER+1
-done
+	if [ `echo -e "$ZPOOLSTATUS" | grep $ZPOOLDRIVE | grep -c AVAIL` -gt 0 ]
+	then
+		DISKSTATUS=$"Spare"
+		SHOWREMOVE=yes
+	fi
+
+
+	get_drive_info
+	echo "<tr><td><a class=\"info\" href=\"javascript:void(0)\"><img class=\"images\" alt=\"\" src=\"/images/submenus/system/$DISKICON\"><span>$DRIVE - $DISKSIZE</span></a> "$DRIVE - $DISKSTATUS"</td><td>$MAKER $DRIVE_SN</td>"
+
+[ $SHOWREMOVE = yes ] && echo "<td>
+<a class=\"info\" href=\"javascript:void(0)\"><input name=\"_SERVERTYPE_'$SERVERTYPE'_SERVERNAME_'$SERVERNAME'_ACTION_removespare_POOL_$POOLNAME"_"DRIVE_$DRIVE"_"DRIVE2_notset"_"\" type=\"image\" class=\"images\" src="'$ICON3'" value=\"\"><span>Remove spare</span></a>
+</td>"
+echo "</tr>"
+	done
+
 echo "</tbody></table><br>"
+#Show any spare drives
+show_spare_drives
+echo "</form><form METHOD=POST ACTION=\"/cgi-bin/admin/zfs_raid_control2.cgi\" target=\"_top\" name = \"frm\">"
+done
 '
 fi
 
